/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class BitStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BitStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_BitStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static BitStream GetInstance() {
    long cPtr = SLikeNetJNI.BitStream_GetInstance();
    return (cPtr == 0) ? null : new BitStream(cPtr, false);
  }

  public static void DestroyInstance(BitStream i) {
    SLikeNetJNI.BitStream_DestroyInstance(BitStream.getCPtr(i), i);
  }

  public BitStream() {
    this(SLikeNetJNI.new_BitStream__SWIG_0(), true);
  }

  public BitStream(long initialBytesToAllocate) {
    this(SLikeNetJNI.new_BitStream__SWIG_1(initialBytesToAllocate), true);
  }

  public BitStream(SWIGTYPE_p_unsigned_char _data, long lengthInBytes, boolean _copyData) {
    this(SLikeNetJNI.new_BitStream__SWIG_2(SWIGTYPE_p_unsigned_char.getCPtr(_data), lengthInBytes, _copyData), true);
  }

  public void Reset() {
    SLikeNetJNI.BitStream_Reset(swigCPtr, this);
  }

  public boolean SerializeFloat16(boolean writeToBitstream, SWIGTYPE_p_float inOutFloat, float floatMin, float floatMax) {
    return SLikeNetJNI.BitStream_SerializeFloat16(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutFloat), floatMin, floatMax);
  }

  public boolean SerializeBits(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutByteArray, SWIGTYPE_p_unsigned___int32 numberOfBitsToSerialize, boolean rightAlignedBits) {
    return SLikeNetJNI.BitStream_SerializeBits__SWIG_0(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutByteArray), SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToSerialize), rightAlignedBits);
  }

  public boolean SerializeBits(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutByteArray, SWIGTYPE_p_unsigned___int32 numberOfBitsToSerialize) {
    return SLikeNetJNI.BitStream_SerializeBits__SWIG_1(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutByteArray), SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToSerialize));
  }

  public boolean Read(SWIGTYPE_p_p_wchar_t varString) {
    return SLikeNetJNI.BitStream_Read__SWIG_1(swigCPtr, this, SWIGTYPE_p_p_wchar_t.getCPtr(varString));
  }

  public boolean Read(SWIGTYPE_p_p_wchar_t varString, long varStringLength) {
    return SLikeNetJNI.BitStream_Read__SWIG_2(swigCPtr, this, SWIGTYPE_p_p_wchar_t.getCPtr(varString), varStringLength);
  }

  public boolean ReadCompressed(SWIGTYPE_p_p_wchar_t varString) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_1(swigCPtr, this, SWIGTYPE_p_p_wchar_t.getCPtr(varString));
  }

  public boolean ReadCompressed(SWIGTYPE_p_p_wchar_t varString, long varStringLength) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_2(swigCPtr, this, SWIGTYPE_p_p_wchar_t.getCPtr(varString), varStringLength);
  }

  public boolean Read(BitStream bitStream, SWIGTYPE_p_unsigned___int32 numberOfBits) {
    return SLikeNetJNI.BitStream_Read__SWIG_3(swigCPtr, this, BitStream.getCPtr(bitStream), bitStream, SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBits));
  }

  public boolean Read(BitStream bitStream) {
    return SLikeNetJNI.BitStream_Read__SWIG_4(swigCPtr, this, BitStream.getCPtr(bitStream), bitStream);
  }

  public void Write(BitStream bitStream, SWIGTYPE_p_unsigned___int32 numberOfBits) {
    SLikeNetJNI.BitStream_Write__SWIG_1(swigCPtr, this, BitStream.getCPtr(bitStream), bitStream, SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBits));
  }

  public void Write(BitStream bitStream) {
    SLikeNetJNI.BitStream_Write__SWIG_2(swigCPtr, this, BitStream.getCPtr(bitStream), bitStream);
  }

  public void WriteFloat16(float x, float floatMin, float floatMax) {
    SLikeNetJNI.BitStream_WriteFloat16(swigCPtr, this, x, floatMin, floatMax);
  }

  public boolean ReadFloat16(SWIGTYPE_p_float outFloat, float floatMin, float floatMax) {
    return SLikeNetJNI.BitStream_ReadFloat16(swigCPtr, this, SWIGTYPE_p_float.getCPtr(outFloat), floatMin, floatMax);
  }

  public void ResetReadPointer() {
    SLikeNetJNI.BitStream_ResetReadPointer(swigCPtr, this);
  }

  public void ResetWritePointer() {
    SLikeNetJNI.BitStream_ResetWritePointer(swigCPtr, this);
  }

  public void AssertStreamEmpty() {
    SLikeNetJNI.BitStream_AssertStreamEmpty(swigCPtr, this);
  }

  public void PrintBits(String out, long outLength) {
    SLikeNetJNI.BitStream_PrintBits__SWIG_0(swigCPtr, this, out, outLength);
  }

  public void PrintBits() {
    SLikeNetJNI.BitStream_PrintBits__SWIG_1(swigCPtr, this);
  }

  public void PrintHex(String out, long outLength) {
    SLikeNetJNI.BitStream_PrintHex__SWIG_0(swigCPtr, this, out, outLength);
  }

  public void PrintHex() {
    SLikeNetJNI.BitStream_PrintHex__SWIG_1(swigCPtr, this);
  }

  public void IgnoreBits(SWIGTYPE_p_unsigned___int32 numberOfBits) {
    SLikeNetJNI.BitStream_IgnoreBits(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBits));
  }

  public void IgnoreBytes(long numberOfBytes) {
    SLikeNetJNI.BitStream_IgnoreBytes(swigCPtr, this, numberOfBytes);
  }

  public void SetWriteOffset(SWIGTYPE_p_unsigned___int32 offset) {
    SLikeNetJNI.BitStream_SetWriteOffset(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(offset));
  }

  public SWIGTYPE_p_unsigned___int32 GetNumberOfBitsUsed() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.BitStream_GetNumberOfBitsUsed(swigCPtr, this), true);
  }

  public SWIGTYPE_p_unsigned___int32 GetWriteOffset() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.BitStream_GetWriteOffset(swigCPtr, this), true);
  }

  public SWIGTYPE_p_unsigned___int32 GetNumberOfBytesUsed() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.BitStream_GetNumberOfBytesUsed(swigCPtr, this), true);
  }

  public SWIGTYPE_p_unsigned___int32 GetReadOffset() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.BitStream_GetReadOffset(swigCPtr, this), true);
  }

  public void SetReadOffset(SWIGTYPE_p_unsigned___int32 newReadOffset) {
    SLikeNetJNI.BitStream_SetReadOffset(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(newReadOffset));
  }

  public SWIGTYPE_p_unsigned___int32 GetNumberOfUnreadBits() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.BitStream_GetNumberOfUnreadBits(swigCPtr, this), true);
  }

  public void SetData(SWIGTYPE_p_unsigned_char inByteArray) {
    SLikeNetJNI.BitStream_SetData(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inByteArray));
  }

  public void WriteBits(SWIGTYPE_p_unsigned_char inByteArray, SWIGTYPE_p_unsigned___int32 numberOfBitsToWrite, boolean rightAlignedBits) {
    SLikeNetJNI.BitStream_WriteBits__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inByteArray), SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToWrite), rightAlignedBits);
  }

  public void WriteBits(SWIGTYPE_p_unsigned_char inByteArray, SWIGTYPE_p_unsigned___int32 numberOfBitsToWrite) {
    SLikeNetJNI.BitStream_WriteBits__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inByteArray), SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToWrite));
  }

  public void WriteAlignedBytes(SWIGTYPE_p_unsigned_char inByteArray, long numberOfBytesToWrite) {
    SLikeNetJNI.BitStream_WriteAlignedBytes(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inByteArray), numberOfBytesToWrite);
  }

  public void EndianSwapBytes(int byteOffset, int length) {
    SLikeNetJNI.BitStream_EndianSwapBytes(swigCPtr, this, byteOffset, length);
  }

  public boolean ReadAlignedBytes(SWIGTYPE_p_unsigned_char inOutByteArray, long numberOfBytesToRead) {
    return SLikeNetJNI.BitStream_ReadAlignedBytes(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inOutByteArray), numberOfBytesToRead);
  }

  public void AlignWriteToByteBoundary() {
    SLikeNetJNI.BitStream_AlignWriteToByteBoundary(swigCPtr, this);
  }

  public void AlignReadToByteBoundary() {
    SLikeNetJNI.BitStream_AlignReadToByteBoundary(swigCPtr, this);
  }

  public boolean ReadBits(SWIGTYPE_p_unsigned_char inOutByteArray, SWIGTYPE_p_unsigned___int32 numberOfBitsToRead, boolean alignBitsToRight) {
    return SLikeNetJNI.BitStream_ReadBits__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inOutByteArray), SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToRead), alignBitsToRight);
  }

  public boolean ReadBits(SWIGTYPE_p_unsigned_char inOutByteArray, SWIGTYPE_p_unsigned___int32 numberOfBitsToRead) {
    return SLikeNetJNI.BitStream_ReadBits__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(inOutByteArray), SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToRead));
  }

  public void Write0() {
    SLikeNetJNI.BitStream_Write0(swigCPtr, this);
  }

  public void Write1() {
    SLikeNetJNI.BitStream_Write1(swigCPtr, this);
  }

  public boolean ReadBit() {
    return SLikeNetJNI.BitStream_ReadBit(swigCPtr, this);
  }

  public void AssertCopyData() {
    SLikeNetJNI.BitStream_AssertCopyData(swigCPtr, this);
  }

  public void SetNumberOfBitsAllocated(SWIGTYPE_p_unsigned___int32 lengthInBits) {
    SLikeNetJNI.BitStream_SetNumberOfBitsAllocated(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(lengthInBits));
  }

  public void AddBitsAndReallocate(SWIGTYPE_p_unsigned___int32 numberOfBitsToWrite) {
    SLikeNetJNI.BitStream_AddBitsAndReallocate(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(numberOfBitsToWrite));
  }

  public SWIGTYPE_p_unsigned___int32 GetNumberOfBitsAllocated() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.BitStream_GetNumberOfBitsAllocated(swigCPtr, this), true);
  }

  public void PadWithZeroToByteLength(long bytes) {
    SLikeNetJNI.BitStream_PadWithZeroToByteLength(swigCPtr, this, bytes);
  }

  public static int NumberOfLeadingZeroes(short x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_0(x);
  }

  public static int NumberOfLeadingZeroes(int x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_1(x);
  }

  public static int NumberOfLeadingZeroes(SWIGTYPE_p_unsigned___int32 x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_2(SWIGTYPE_p_unsigned___int32.getCPtr(x));
  }

  public static int NumberOfLeadingZeroes(java.math.BigInteger x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_3(x);
  }

  public static int NumberOfLeadingZeroes(byte x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_4(x);
  }

  public static int NumberOfLeadingZeroes(SWIGTYPE_p___int32 x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_6(SWIGTYPE_p___int32.getCPtr(x));
  }

  public static int NumberOfLeadingZeroes(long x) {
    return SLikeNetJNI.BitStream_NumberOfLeadingZeroes__SWIG_7(x);
  }

  public void Write(String inStringVar) {
    SLikeNetJNI.BitStream_Write__SWIG_3(swigCPtr, this, inStringVar);
  }

  public void Write(SWIGTYPE_p_wchar_t inStringVar) {
    SLikeNetJNI.BitStream_Write__SWIG_4(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(inStringVar));
  }

  public void WriteCompressed(String inStringVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_1(swigCPtr, this, inStringVar);
  }

  public void WriteCompressed(SWIGTYPE_p_wchar_t inStringVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_2(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(inStringVar));
  }

  public static boolean DoEndianSwap() {
    return SLikeNetJNI.BitStream_DoEndianSwap();
  }

  public static boolean IsBigEndian() {
    return SLikeNetJNI.BitStream_IsBigEndian();
  }

  public static boolean IsNetworkOrder() {
    return SLikeNetJNI.BitStream_IsNetworkOrder();
  }

  public static boolean IsNetworkOrderInternal() {
    return SLikeNetJNI.BitStream_IsNetworkOrderInternal();
  }

  public static void ReverseBytes(SWIGTYPE_p_unsigned_char inByteArray, SWIGTYPE_p_unsigned_char inOutByteArray, long length) {
    SLikeNetJNI.BitStream_ReverseBytes(SWIGTYPE_p_unsigned_char.getCPtr(inByteArray), SWIGTYPE_p_unsigned_char.getCPtr(inOutByteArray), length);
  }

  public static void ReverseBytesInPlace(SWIGTYPE_p_unsigned_char inOutData, long length) {
    SLikeNetJNI.BitStream_ReverseBytesInPlace(SWIGTYPE_p_unsigned_char.getCPtr(inOutData), length);
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_bool inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_1(swigCPtr, this, writeToBitstream, SWIGTYPE_p_bool.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_2(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_short inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_3(swigCPtr, this, writeToBitstream, SWIGTYPE_p_short.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_unsigned_short inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_4(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_short.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_long inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_5(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_long_long inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_6(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long_long.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, SWIGTYPE_p_float inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_7(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutTemplateVar));
  }

  public boolean Serialize(boolean writeToBitstream, RakString inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_8(swigCPtr, this, writeToBitstream, RakString.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean Serialize(boolean writeToBitstream, RakNetGUID inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_9(swigCPtr, this, writeToBitstream, RakNetGUID.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean Serialize(boolean writeToBitstream, uint24_t inOutTemplateVar) {
    return SLikeNetJNI.BitStream_Serialize__SWIG_10(swigCPtr, this, writeToBitstream, uint24_t.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_bool inOutCurrentValue, boolean lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_2(swigCPtr, this, writeToBitstream, SWIGTYPE_p_bool.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_bool inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_3(swigCPtr, this, writeToBitstream, SWIGTYPE_p_bool.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutCurrentValue, short lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_4(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_5(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_short inOutCurrentValue, short lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_6(swigCPtr, this, writeToBitstream, SWIGTYPE_p_short.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_short inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_7(swigCPtr, this, writeToBitstream, SWIGTYPE_p_short.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_short inOutCurrentValue, int lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_8(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_short.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_short inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_9(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_short.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_long inOutCurrentValue, int lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_10(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_long inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_11(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_long_long inOutCurrentValue, long lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_12(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long_long.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_long_long inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_13(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long_long.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_float inOutCurrentValue, float lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_14(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, SWIGTYPE_p_float inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_15(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutCurrentValue));
  }

  public boolean SerializeDelta(boolean writeToBitstream, RakString inOutCurrentValue, RakString lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_16(swigCPtr, this, writeToBitstream, RakString.getCPtr(inOutCurrentValue), inOutCurrentValue, RakString.getCPtr(lastValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, RakString inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_17(swigCPtr, this, writeToBitstream, RakString.getCPtr(inOutCurrentValue), inOutCurrentValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, RakNetGUID inOutCurrentValue, RakNetGUID lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_18(swigCPtr, this, writeToBitstream, RakNetGUID.getCPtr(inOutCurrentValue), inOutCurrentValue, RakNetGUID.getCPtr(lastValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, RakNetGUID inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_19(swigCPtr, this, writeToBitstream, RakNetGUID.getCPtr(inOutCurrentValue), inOutCurrentValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, uint24_t inOutCurrentValue, uint24_t lastValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_20(swigCPtr, this, writeToBitstream, uint24_t.getCPtr(inOutCurrentValue), inOutCurrentValue, uint24_t.getCPtr(lastValue), lastValue);
  }

  public boolean SerializeDelta(boolean writeToBitstream, uint24_t inOutCurrentValue) {
    return SLikeNetJNI.BitStream_SerializeDelta__SWIG_21(swigCPtr, this, writeToBitstream, uint24_t.getCPtr(inOutCurrentValue), inOutCurrentValue);
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_bool inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_1(swigCPtr, this, writeToBitstream, SWIGTYPE_p_bool.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_2(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_short inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_3(swigCPtr, this, writeToBitstream, SWIGTYPE_p_short.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_unsigned_short inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_4(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_short.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_long inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_5(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_long_long inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_6(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long_long.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, SWIGTYPE_p_float inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_7(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressed(boolean writeToBitstream, RakString inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_8(swigCPtr, this, writeToBitstream, RakString.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean SerializeCompressed(boolean writeToBitstream, RakNetGUID inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_9(swigCPtr, this, writeToBitstream, RakNetGUID.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean SerializeCompressed(boolean writeToBitstream, uint24_t inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressed__SWIG_10(swigCPtr, this, writeToBitstream, uint24_t.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_bool inOutCurrentValue, boolean lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_2(swigCPtr, this, writeToBitstream, SWIGTYPE_p_bool.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_bool inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_3(swigCPtr, this, writeToBitstream, SWIGTYPE_p_bool.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutCurrentValue, short lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_4(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_char inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_5(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_char.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_short inOutCurrentValue, short lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_6(swigCPtr, this, writeToBitstream, SWIGTYPE_p_short.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_short inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_7(swigCPtr, this, writeToBitstream, SWIGTYPE_p_short.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_short inOutCurrentValue, int lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_8(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_short.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_unsigned_short inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_9(swigCPtr, this, writeToBitstream, SWIGTYPE_p_unsigned_short.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_long inOutCurrentValue, int lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_10(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_long inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_11(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_long_long inOutCurrentValue, long lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_12(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long_long.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_long_long inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_13(swigCPtr, this, writeToBitstream, SWIGTYPE_p_long_long.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_float inOutCurrentValue, float lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_14(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutCurrentValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, SWIGTYPE_p_float inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_15(swigCPtr, this, writeToBitstream, SWIGTYPE_p_float.getCPtr(inOutTemplateVar));
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, RakString inOutCurrentValue, RakString lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_16(swigCPtr, this, writeToBitstream, RakString.getCPtr(inOutCurrentValue), inOutCurrentValue, RakString.getCPtr(lastValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, RakString inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_17(swigCPtr, this, writeToBitstream, RakString.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, RakNetGUID inOutCurrentValue, RakNetGUID lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_18(swigCPtr, this, writeToBitstream, RakNetGUID.getCPtr(inOutCurrentValue), inOutCurrentValue, RakNetGUID.getCPtr(lastValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, RakNetGUID inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_19(swigCPtr, this, writeToBitstream, RakNetGUID.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, uint24_t inOutCurrentValue, uint24_t lastValue) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_20(swigCPtr, this, writeToBitstream, uint24_t.getCPtr(inOutCurrentValue), inOutCurrentValue, uint24_t.getCPtr(lastValue), lastValue);
  }

  public boolean SerializeCompressedDelta(boolean writeToBitstream, uint24_t inOutTemplateVar) {
    return SLikeNetJNI.BitStream_SerializeCompressedDelta__SWIG_21(swigCPtr, this, writeToBitstream, uint24_t.getCPtr(inOutTemplateVar), inOutTemplateVar);
  }

  public void Write(boolean inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_7(swigCPtr, this, inTemplateVar);
  }

  public void Write(short inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_8(swigCPtr, this, inTemplateVar);
  }

  public void Write(char inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_9(swigCPtr, this, inTemplateVar);
  }

  public void Write(int inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_11(swigCPtr, this, inTemplateVar);
  }

  public void Write(long inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_13(swigCPtr, this, inTemplateVar);
  }

  public void Write(float inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_14(swigCPtr, this, inTemplateVar);
  }

  public void Write(RakString inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_15(swigCPtr, this, RakString.getCPtr(inTemplateVar), inTemplateVar);
  }

  public void Write(RakNetGUID inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_16(swigCPtr, this, RakNetGUID.getCPtr(inTemplateVar), inTemplateVar);
  }

  public void Write(uint24_t inTemplateVar) {
    SLikeNetJNI.BitStream_Write__SWIG_17(swigCPtr, this, uint24_t.getCPtr(inTemplateVar), inTemplateVar);
  }

  public void WriteDelta(String currentValue, String lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_2(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(String currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_3(swigCPtr, this, currentValue);
  }

  public void WriteDelta(boolean currentValue, boolean lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_4(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(boolean currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_5(swigCPtr, this, currentValue);
  }

  public void WriteDelta(short currentValue, short lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_6(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(short currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_7(swigCPtr, this, currentValue);
  }

  public void WriteDelta(char currentValue, char lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_8(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(char currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_9(swigCPtr, this, currentValue);
  }

  public void WriteDelta(int currentValue, int lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_12(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(int currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_13(swigCPtr, this, currentValue);
  }

  public void WriteDelta(long currentValue, long lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_16(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(long currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_17(swigCPtr, this, currentValue);
  }

  public void WriteDelta(float currentValue, float lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_18(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteDelta(float currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_19(swigCPtr, this, currentValue);
  }

  public void WriteDelta(RakString currentValue, RakString lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_20(swigCPtr, this, RakString.getCPtr(currentValue), currentValue, RakString.getCPtr(lastValue), lastValue);
  }

  public void WriteDelta(RakString currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_21(swigCPtr, this, RakString.getCPtr(currentValue), currentValue);
  }

  public void WriteDelta(RakNetGUID currentValue, RakNetGUID lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_22(swigCPtr, this, RakNetGUID.getCPtr(currentValue), currentValue, RakNetGUID.getCPtr(lastValue), lastValue);
  }

  public void WriteDelta(RakNetGUID currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_23(swigCPtr, this, RakNetGUID.getCPtr(currentValue), currentValue);
  }

  public void WriteDelta(uint24_t currentValue, uint24_t lastValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_24(swigCPtr, this, uint24_t.getCPtr(currentValue), currentValue, uint24_t.getCPtr(lastValue), lastValue);
  }

  public void WriteDelta(uint24_t currentValue) {
    SLikeNetJNI.BitStream_WriteDelta__SWIG_25(swigCPtr, this, uint24_t.getCPtr(currentValue), currentValue);
  }

  public void WriteCompressed(boolean inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_5(swigCPtr, this, inTemplateVar);
  }

  public void WriteCompressed(short inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_6(swigCPtr, this, inTemplateVar);
  }

  public void WriteCompressed(char inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_7(swigCPtr, this, inTemplateVar);
  }

  public void WriteCompressed(int inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_9(swigCPtr, this, inTemplateVar);
  }

  public void WriteCompressed(long inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_11(swigCPtr, this, inTemplateVar);
  }

  public void WriteCompressed(float inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_12(swigCPtr, this, inTemplateVar);
  }

  public void WriteCompressed(RakString inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_13(swigCPtr, this, RakString.getCPtr(inTemplateVar), inTemplateVar);
  }

  public void WriteCompressed(RakNetGUID inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_14(swigCPtr, this, RakNetGUID.getCPtr(inTemplateVar), inTemplateVar);
  }

  public void WriteCompressed(uint24_t inTemplateVar) {
    SLikeNetJNI.BitStream_WriteCompressed__SWIG_15(swigCPtr, this, uint24_t.getCPtr(inTemplateVar), inTemplateVar);
  }

  public void WriteCompressedDelta(String currentValue, String lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_2(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(String currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_3(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(boolean currentValue, boolean lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_4(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(boolean currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_5(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(short currentValue, short lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_6(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(short currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_7(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(char currentValue, char lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_8(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(char currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_9(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(int currentValue, int lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_12(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(int currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_13(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(long currentValue, long lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_16(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(long currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_17(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(float currentValue, float lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_18(swigCPtr, this, currentValue, lastValue);
  }

  public void WriteCompressedDelta(float currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_19(swigCPtr, this, currentValue);
  }

  public void WriteCompressedDelta(RakString currentValue, RakString lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_20(swigCPtr, this, RakString.getCPtr(currentValue), currentValue, RakString.getCPtr(lastValue), lastValue);
  }

  public void WriteCompressedDelta(RakString currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_21(swigCPtr, this, RakString.getCPtr(currentValue), currentValue);
  }

  public void WriteCompressedDelta(RakNetGUID currentValue, RakNetGUID lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_22(swigCPtr, this, RakNetGUID.getCPtr(currentValue), currentValue, RakNetGUID.getCPtr(lastValue), lastValue);
  }

  public void WriteCompressedDelta(RakNetGUID currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_23(swigCPtr, this, RakNetGUID.getCPtr(currentValue), currentValue);
  }

  public void WriteCompressedDelta(uint24_t currentValue, uint24_t lastValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_24(swigCPtr, this, uint24_t.getCPtr(currentValue), currentValue, uint24_t.getCPtr(lastValue), lastValue);
  }

  public void WriteCompressedDelta(uint24_t currentValue) {
    SLikeNetJNI.BitStream_WriteCompressedDelta__SWIG_25(swigCPtr, this, uint24_t.getCPtr(currentValue), currentValue);
  }

  public boolean Read(SWIGTYPE_p_bool outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_5(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(outTemplateVar));
  }

  public boolean Read(SWIGTYPE_p_unsigned_char outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_6(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(outTemplateVar));
  }

  public boolean Read(SWIGTYPE_p_short outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_7(swigCPtr, this, SWIGTYPE_p_short.getCPtr(outTemplateVar));
  }

  public boolean Read(SWIGTYPE_p_unsigned_short outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_8(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(outTemplateVar));
  }

  public boolean Read(SWIGTYPE_p_long outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_9(swigCPtr, this, SWIGTYPE_p_long.getCPtr(outTemplateVar));
  }

  public boolean Read(SWIGTYPE_p_long_long outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_10(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(outTemplateVar));
  }

  public boolean Read(SWIGTYPE_p_float outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_11(swigCPtr, this, SWIGTYPE_p_float.getCPtr(outTemplateVar));
  }

  public boolean Read(RakString outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_12(swigCPtr, this, RakString.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean Read(RakNetGUID outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_13(swigCPtr, this, RakNetGUID.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean Read(uint24_t outTemplateVar) {
    return SLikeNetJNI.BitStream_Read__SWIG_14(swigCPtr, this, uint24_t.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadDelta(SWIGTYPE_p_bool outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_1(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(SWIGTYPE_p_unsigned_char outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_2(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(SWIGTYPE_p_short outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_3(swigCPtr, this, SWIGTYPE_p_short.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(SWIGTYPE_p_unsigned_short outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_4(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(SWIGTYPE_p_long outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_5(swigCPtr, this, SWIGTYPE_p_long.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(SWIGTYPE_p_long_long outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_6(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(SWIGTYPE_p_float outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_7(swigCPtr, this, SWIGTYPE_p_float.getCPtr(outTemplateVar));
  }

  public boolean ReadDelta(RakString outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_8(swigCPtr, this, RakString.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadDelta(RakNetGUID outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_9(swigCPtr, this, RakNetGUID.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadDelta(uint24_t outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadDelta__SWIG_10(swigCPtr, this, uint24_t.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadCompressed(SWIGTYPE_p_bool outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_3(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(SWIGTYPE_p_unsigned_char outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_4(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(SWIGTYPE_p_short outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_5(swigCPtr, this, SWIGTYPE_p_short.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(SWIGTYPE_p_unsigned_short outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_6(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(SWIGTYPE_p_long outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_7(swigCPtr, this, SWIGTYPE_p_long.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(SWIGTYPE_p_long_long outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_8(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(SWIGTYPE_p_float outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_9(swigCPtr, this, SWIGTYPE_p_float.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressed(RakString outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_10(swigCPtr, this, RakString.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadCompressed(RakNetGUID outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_11(swigCPtr, this, RakNetGUID.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadCompressed(uint24_t outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressed__SWIG_12(swigCPtr, this, uint24_t.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_bool outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_1(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_unsigned_char outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_2(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_short outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_3(swigCPtr, this, SWIGTYPE_p_short.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_unsigned_short outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_4(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_long outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_5(swigCPtr, this, SWIGTYPE_p_long.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_long_long outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_6(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(SWIGTYPE_p_float outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_7(swigCPtr, this, SWIGTYPE_p_float.getCPtr(outTemplateVar));
  }

  public boolean ReadCompressedDelta(RakString outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_8(swigCPtr, this, RakString.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadCompressedDelta(RakNetGUID outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_9(swigCPtr, this, RakNetGUID.getCPtr(outTemplateVar), outTemplateVar);
  }

  public boolean ReadCompressedDelta(uint24_t outTemplateVar) {
    return SLikeNetJNI.BitStream_ReadCompressedDelta__SWIG_10(swigCPtr, this, uint24_t.getCPtr(outTemplateVar), outTemplateVar);
  }

}
