/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class ByteQueue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ByteQueue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteQueue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_ByteQueue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ByteQueue() {
    this(SLikeNetJNI.new_ByteQueue(), true);
  }

  public long GetBytesWritten() {
    return SLikeNetJNI.ByteQueue_GetBytesWritten(swigCPtr, this);
  }

  public void IncrementReadOffset(long length) {
    SLikeNetJNI.ByteQueue_IncrementReadOffset(swigCPtr, this, length);
  }

  public void DecrementReadOffset(long length) {
    SLikeNetJNI.ByteQueue_DecrementReadOffset(swigCPtr, this, length);
  }

  public void Clear(String file, long line) {
    SLikeNetJNI.ByteQueue_Clear(swigCPtr, this, file, line);
  }

  public void Print() {
    SLikeNetJNI.ByteQueue_Print(swigCPtr, this);
  }

}
