/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class ByteArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ByteArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_ByteArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public short getByteAt(long pos) {
    return SLikeNetJNI.ByteArray_getByteAt(swigCPtr, this, pos);
  }

  public void setByteAt(long pos, short _byte) {
    SLikeNetJNI.ByteArray_setByteAt(swigCPtr, this, pos, _byte);
  }

  public long getSize() {
    return SLikeNetJNI.ByteArray_getSize(swigCPtr, this);
  }

  public ByteArray(long size, SWIGTYPE_p_unsigned_char data) {
    this(SLikeNetJNI.new_ByteArray(size, SWIGTYPE_p_unsigned_char.getCPtr(data)), true);
  }

}
