/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public final class ConnectionState {
  public final static ConnectionState IS_PENDING = new ConnectionState("IS_PENDING");
  public final static ConnectionState IS_CONNECTING = new ConnectionState("IS_CONNECTING");
  public final static ConnectionState IS_CONNECTED = new ConnectionState("IS_CONNECTED");
  public final static ConnectionState IS_DISCONNECTING = new ConnectionState("IS_DISCONNECTING");
  public final static ConnectionState IS_SILENTLY_DISCONNECTING = new ConnectionState("IS_SILENTLY_DISCONNECTING");
  public final static ConnectionState IS_DISCONNECTED = new ConnectionState("IS_DISCONNECTED");
  public final static ConnectionState IS_NOT_CONNECTED = new ConnectionState("IS_NOT_CONNECTED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ConnectionState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ConnectionState.class + " with value " + swigValue);
  }

  private ConnectionState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ConnectionState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ConnectionState(String swigName, ConnectionState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ConnectionState[] swigValues = { IS_PENDING, IS_CONNECTING, IS_CONNECTED, IS_DISCONNECTING, IS_SILENTLY_DISCONNECTING, IS_DISCONNECTED, IS_NOT_CONNECTED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

