/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class FileListProgress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileListProgress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileListProgress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_FileListProgress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static FileListProgress GetInstance() {
    long cPtr = SLikeNetJNI.FileListProgress_GetInstance();
    return (cPtr == 0) ? null : new FileListProgress(cPtr, false);
  }

  public static void DestroyInstance(FileListProgress i) {
    SLikeNetJNI.FileListProgress_DestroyInstance(FileListProgress.getCPtr(i), i);
  }

  public FileListProgress() {
    this(SLikeNetJNI.new_FileListProgress(), true);
  }

  public void OnAddFilesFromDirectoryStarted(FileList fileList, String dir) {
    SLikeNetJNI.FileListProgress_OnAddFilesFromDirectoryStarted(swigCPtr, this, FileList.getCPtr(fileList), fileList, dir);
  }

  public void OnDirectory(FileList fileList, String dir, long directoriesRemaining) {
    SLikeNetJNI.FileListProgress_OnDirectory(swigCPtr, this, FileList.getCPtr(fileList), fileList, dir, directoriesRemaining);
  }

  public void OnFile(FileList fileList, String dir, String fileName, long fileSize) {
    SLikeNetJNI.FileListProgress_OnFile(swigCPtr, this, FileList.getCPtr(fileList), fileList, dir, fileName, fileSize);
  }

  public void OnFilePush(String fileName, long fileLengthBytes, long offset, long bytesBeingSent, boolean done, SystemAddress targetSystem, int setId) {
    SLikeNetJNI.FileListProgress_OnFilePush(swigCPtr, this, fileName, fileLengthBytes, offset, bytesBeingSent, done, SystemAddress.getCPtr(targetSystem), targetSystem, setId);
  }

  public void OnFilePushesComplete(SystemAddress systemAddress, int setId) {
    SLikeNetJNI.FileListProgress_OnFilePushesComplete(swigCPtr, this, SystemAddress.getCPtr(systemAddress), systemAddress, setId);
  }

  public void OnSendAborted(SystemAddress systemAddress) {
    SLikeNetJNI.FileListProgress_OnSendAborted(swigCPtr, this, SystemAddress.getCPtr(systemAddress), systemAddress);
  }

}
