/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class FileListNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileListNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileListNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_FileListNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFilename(RakString value) {
    SLikeNetJNI.FileListNode_filename_set(swigCPtr, this, RakString.getCPtr(value), value);
  }

  public RakString getFilename() {
    long cPtr = SLikeNetJNI.FileListNode_filename_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RakString(cPtr, false);
  }

  public void setFullPathToFile(RakString value) {
    SLikeNetJNI.FileListNode_fullPathToFile_set(swigCPtr, this, RakString.getCPtr(value), value);
  }

  public RakString getFullPathToFile() {
    long cPtr = SLikeNetJNI.FileListNode_fullPathToFile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RakString(cPtr, false);
  }

  public void setData(String value) {
    SLikeNetJNI.FileListNode_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return SLikeNetJNI.FileListNode_data_get(swigCPtr, this);
  }

  public void setDataLengthBytes(SWIGTYPE_p_unsigned___int32 value) {
    SLikeNetJNI.FileListNode_dataLengthBytes_set(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned___int32 getDataLengthBytes() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.FileListNode_dataLengthBytes_get(swigCPtr, this), true);
  }

  public void setFileLengthBytes(long value) {
    SLikeNetJNI.FileListNode_fileLengthBytes_set(swigCPtr, this, value);
  }

  public long getFileLengthBytes() {
    return SLikeNetJNI.FileListNode_fileLengthBytes_get(swigCPtr, this);
  }

  public void setContext(FileListNodeContext value) {
    SLikeNetJNI.FileListNode_context_set(swigCPtr, this, FileListNodeContext.getCPtr(value), value);
  }

  public FileListNodeContext getContext() {
    long cPtr = SLikeNetJNI.FileListNode_context_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FileListNodeContext(cPtr, false);
  }

  public void setIsAReference(boolean value) {
    SLikeNetJNI.FileListNode_isAReference_set(swigCPtr, this, value);
  }

  public boolean getIsAReference() {
    return SLikeNetJNI.FileListNode_isAReference_get(swigCPtr, this);
  }

  public FileListNode() {
    this(SLikeNetJNI.new_FileListNode(), true);
  }

}
