/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class FLP_Printf extends FileListProgress {
  private transient long swigCPtr;

  protected FLP_Printf(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.FLP_Printf_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FLP_Printf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_FLP_Printf(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static FLP_Printf GetInstance() {
    long cPtr = SLikeNetJNI.FLP_Printf_GetInstance();
    return (cPtr == 0) ? null : new FLP_Printf(cPtr, false);
  }

  public static void DestroyInstance(FLP_Printf i) {
    SLikeNetJNI.FLP_Printf_DestroyInstance(FLP_Printf.getCPtr(i), i);
  }

  public FLP_Printf() {
    this(SLikeNetJNI.new_FLP_Printf(), true);
  }

  public void OnAddFilesFromDirectoryStarted(FileList fileList, String dir) {
    SLikeNetJNI.FLP_Printf_OnAddFilesFromDirectoryStarted(swigCPtr, this, FileList.getCPtr(fileList), fileList, dir);
  }

  public void OnDirectory(FileList fileList, String dir, long directoriesRemaining) {
    SLikeNetJNI.FLP_Printf_OnDirectory(swigCPtr, this, FileList.getCPtr(fileList), fileList, dir, directoriesRemaining);
  }

  public void OnFilePushesComplete(SystemAddress systemAddress, int setID) {
    SLikeNetJNI.FLP_Printf_OnFilePushesComplete(swigCPtr, this, SystemAddress.getCPtr(systemAddress), systemAddress, setID);
  }

  public void OnSendAborted(SystemAddress systemAddress) {
    SLikeNetJNI.FLP_Printf_OnSendAborted(swigCPtr, this, SystemAddress.getCPtr(systemAddress), systemAddress);
  }

}
