/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class LogCommandParser extends CommandParserInterface {
  private transient long swigCPtr;

  protected LogCommandParser(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.LogCommandParser_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogCommandParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_LogCommandParser(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static LogCommandParser GetInstance() {
    long cPtr = SLikeNetJNI.LogCommandParser_GetInstance();
    return (cPtr == 0) ? null : new LogCommandParser(cPtr, false);
  }

  public static void DestroyInstance(LogCommandParser i) {
    SLikeNetJNI.LogCommandParser_DestroyInstance(LogCommandParser.getCPtr(i), i);
  }

  public LogCommandParser() {
    this(SLikeNetJNI.new_LogCommandParser(), true);
  }

  public boolean OnCommand(String command, long numParameters, SWIGTYPE_p_p_char parameterList, TransportInterface transport, SystemAddress systemAddress, String originalString) {
    return SLikeNetJNI.LogCommandParser_OnCommand(swigCPtr, this, command, numParameters, SWIGTYPE_p_p_char.getCPtr(parameterList), TransportInterface.getCPtr(transport), transport, SystemAddress.getCPtr(systemAddress), systemAddress, originalString);
  }

  public String GetName() {
    return SLikeNetJNI.LogCommandParser_GetName(swigCPtr, this);
  }

  public void SendHelp(TransportInterface transport, SystemAddress systemAddress) {
    SLikeNetJNI.LogCommandParser_SendHelp(swigCPtr, this, TransportInterface.getCPtr(transport), transport, SystemAddress.getCPtr(systemAddress), systemAddress);
  }

  public void AddChannel(String channelName) {
    SLikeNetJNI.LogCommandParser_AddChannel(swigCPtr, this, channelName);
  }

  public void WriteLog(String channelName, String format) {
    SLikeNetJNI.LogCommandParser_WriteLog(swigCPtr, this, channelName, format);
  }

  public void OnNewIncomingConnection(SystemAddress systemAddress, TransportInterface transport) {
    SLikeNetJNI.LogCommandParser_OnNewIncomingConnection(swigCPtr, this, SystemAddress.getCPtr(systemAddress), systemAddress, TransportInterface.getCPtr(transport), transport);
  }

  public void OnConnectionLost(SystemAddress systemAddress, TransportInterface transport) {
    SLikeNetJNI.LogCommandParser_OnConnectionLost(swigCPtr, this, SystemAddress.getCPtr(systemAddress), systemAddress, TransportInterface.getCPtr(transport), transport);
  }

  public void OnTransportChange(TransportInterface transport) {
    SLikeNetJNI.LogCommandParser_OnTransportChange(swigCPtr, this, TransportInterface.getCPtr(transport), transport);
  }

}
