/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public final class MultilistType {
  public final static MultilistType ML_UNORDERED_LIST = new MultilistType("ML_UNORDERED_LIST");
  public final static MultilistType ML_STACK = new MultilistType("ML_STACK");
  public final static MultilistType ML_QUEUE = new MultilistType("ML_QUEUE");
  public final static MultilistType ML_ORDERED_LIST = new MultilistType("ML_ORDERED_LIST");
  public final static MultilistType ML_VARIABLE_DURING_RUNTIME = new MultilistType("ML_VARIABLE_DURING_RUNTIME");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MultilistType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MultilistType.class + " with value " + swigValue);
  }

  private MultilistType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MultilistType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MultilistType(String swigName, MultilistType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MultilistType[] swigValues = { ML_UNORDERED_LIST, ML_STACK, ML_QUEUE, ML_ORDERED_LIST, ML_VARIABLE_DURING_RUNTIME };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

