/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class NatPunchthroughServerDebugInterface_Printf extends NatPunchthroughServerDebugInterface {
  private transient long swigCPtr;

  protected NatPunchthroughServerDebugInterface_Printf(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.NatPunchthroughServerDebugInterface_Printf_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NatPunchthroughServerDebugInterface_Printf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_NatPunchthroughServerDebugInterface_Printf(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void OnServerMessage(String msg) {
    SLikeNetJNI.NatPunchthroughServerDebugInterface_Printf_OnServerMessage(swigCPtr, this, msg);
  }

  public NatPunchthroughServerDebugInterface_Printf() {
    this(SLikeNetJNI.new_NatPunchthroughServerDebugInterface_Printf(), true);
  }

}
