/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class NetworkIDManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NetworkIDManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetworkIDManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_NetworkIDManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static NetworkIDManager GetInstance() {
    long cPtr = SLikeNetJNI.NetworkIDManager_GetInstance();
    return (cPtr == 0) ? null : new NetworkIDManager(cPtr, false);
  }

  public static void DestroyInstance(NetworkIDManager i) {
    SLikeNetJNI.NetworkIDManager_DestroyInstance(NetworkIDManager.getCPtr(i), i);
  }

  public NetworkIDManager() {
    this(SLikeNetJNI.new_NetworkIDManager(), true);
  }

  public void Clear() {
    SLikeNetJNI.NetworkIDManager_Clear(swigCPtr, this);
  }

  public NetworkIDObject GET_BASE_OBJECT_FROM_ID(java.math.BigInteger x) {
    long cPtr = SLikeNetJNI.NetworkIDManager_GET_BASE_OBJECT_FROM_ID(swigCPtr, this, x);
    return (cPtr == 0) ? null : new NetworkIDObject(cPtr, false);
  }

}
