/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class NetworkIDObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NetworkIDObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetworkIDObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_NetworkIDObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NetworkIDObject() {
    this(SLikeNetJNI.new_NetworkIDObject(), true);
  }

  public void SetNetworkIDManager(NetworkIDManager manager) {
    SLikeNetJNI.NetworkIDObject_SetNetworkIDManager(swigCPtr, this, NetworkIDManager.getCPtr(manager), manager);
  }

  public NetworkIDManager GetNetworkIDManager() {
    long cPtr = SLikeNetJNI.NetworkIDObject_GetNetworkIDManager(swigCPtr, this);
    return (cPtr == 0) ? null : new NetworkIDManager(cPtr, false);
  }

  public java.math.BigInteger GetNetworkID() {
    return SLikeNetJNI.NetworkIDObject_GetNetworkID(swigCPtr, this);
  }

  public void SetNetworkID(java.math.BigInteger id) {
    SLikeNetJNI.NetworkIDObject_SetNetworkID(swigCPtr, this, id);
  }

}
