/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public final class OutOfBandIdentifiers {
  public final static OutOfBandIdentifiers ID_NAT_ESTABLISH_UNIDIRECTIONAL = new OutOfBandIdentifiers("ID_NAT_ESTABLISH_UNIDIRECTIONAL");
  public final static OutOfBandIdentifiers ID_NAT_ESTABLISH_BIDIRECTIONAL = new OutOfBandIdentifiers("ID_NAT_ESTABLISH_BIDIRECTIONAL");
  public final static OutOfBandIdentifiers ID_NAT_TYPE_DETECT = new OutOfBandIdentifiers("ID_NAT_TYPE_DETECT");
  public final static OutOfBandIdentifiers ID_ROUTER_2_REPLY_TO_SENDER_PORT = new OutOfBandIdentifiers("ID_ROUTER_2_REPLY_TO_SENDER_PORT");
  public final static OutOfBandIdentifiers ID_ROUTER_2_REPLY_TO_SPECIFIED_PORT = new OutOfBandIdentifiers("ID_ROUTER_2_REPLY_TO_SPECIFIED_PORT");
  public final static OutOfBandIdentifiers ID_ROUTER_2_MINI_PUNCH_REPLY = new OutOfBandIdentifiers("ID_ROUTER_2_MINI_PUNCH_REPLY");
  public final static OutOfBandIdentifiers ID_ROUTER_2_MINI_PUNCH_REPLY_BOUNCE = new OutOfBandIdentifiers("ID_ROUTER_2_MINI_PUNCH_REPLY_BOUNCE");
  public final static OutOfBandIdentifiers ID_XBOX_360_VOICE = new OutOfBandIdentifiers("ID_XBOX_360_VOICE");
  public final static OutOfBandIdentifiers ID_XBOX_360_GET_NETWORK_ROOM = new OutOfBandIdentifiers("ID_XBOX_360_GET_NETWORK_ROOM");
  public final static OutOfBandIdentifiers ID_XBOX_360_RETURN_NETWORK_ROOM = new OutOfBandIdentifiers("ID_XBOX_360_RETURN_NETWORK_ROOM");
  public final static OutOfBandIdentifiers ID_NAT_PING = new OutOfBandIdentifiers("ID_NAT_PING");
  public final static OutOfBandIdentifiers ID_NAT_PONG = new OutOfBandIdentifiers("ID_NAT_PONG");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OutOfBandIdentifiers swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OutOfBandIdentifiers.class + " with value " + swigValue);
  }

  private OutOfBandIdentifiers(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OutOfBandIdentifiers(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OutOfBandIdentifiers(String swigName, OutOfBandIdentifiers swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OutOfBandIdentifiers[] swigValues = { ID_NAT_ESTABLISH_UNIDIRECTIONAL, ID_NAT_ESTABLISH_BIDIRECTIONAL, ID_NAT_TYPE_DETECT, ID_ROUTER_2_REPLY_TO_SENDER_PORT, ID_ROUTER_2_REPLY_TO_SPECIFIED_PORT, ID_ROUTER_2_MINI_PUNCH_REPLY, ID_ROUTER_2_MINI_PUNCH_REPLY_BOUNCE, ID_XBOX_360_VOICE, ID_XBOX_360_GET_NETWORK_ROOM, ID_XBOX_360_RETURN_NETWORK_ROOM, ID_NAT_PING, ID_NAT_PONG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

