/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class PacketConsoleLogger extends PacketLogger {
  private transient long swigCPtr;

  protected PacketConsoleLogger(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.PacketConsoleLogger_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PacketConsoleLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_PacketConsoleLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PacketConsoleLogger() {
    this(SLikeNetJNI.new_PacketConsoleLogger(), true);
  }

  public void SetLogCommandParser(LogCommandParser lcp) {
    SLikeNetJNI.PacketConsoleLogger_SetLogCommandParser(swigCPtr, this, LogCommandParser.getCPtr(lcp), lcp);
  }

  public void WriteLog(String str) {
    SLikeNetJNI.PacketConsoleLogger_WriteLog(swigCPtr, this, str);
  }

}
