/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class PacketFileLogger extends PacketLogger {
  private transient long swigCPtr;

  protected PacketFileLogger(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.PacketFileLogger_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PacketFileLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_PacketFileLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static PacketFileLogger GetInstance() {
    long cPtr = SLikeNetJNI.PacketFileLogger_GetInstance();
    return (cPtr == 0) ? null : new PacketFileLogger(cPtr, false);
  }

  public static void DestroyInstance(PacketFileLogger i) {
    SLikeNetJNI.PacketFileLogger_DestroyInstance(PacketFileLogger.getCPtr(i), i);
  }

  public PacketFileLogger() {
    this(SLikeNetJNI.new_PacketFileLogger(), true);
  }

  public void StartLog(String filenamePrefix) {
    SLikeNetJNI.PacketFileLogger_StartLog(swigCPtr, this, filenamePrefix);
  }

  public void WriteLog(String str) {
    SLikeNetJNI.PacketFileLogger_WriteLog(swigCPtr, this, str);
  }

}
