/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class PacketLogger extends PluginInterface2 {
  private transient long swigCPtr;

  protected PacketLogger(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.PacketLogger_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PacketLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_PacketLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static PacketLogger GetInstance() {
    long cPtr = SLikeNetJNI.PacketLogger_GetInstance();
    return (cPtr == 0) ? null : new PacketLogger(cPtr, false);
  }

  public static void DestroyInstance(PacketLogger i) {
    SLikeNetJNI.PacketLogger_DestroyInstance(PacketLogger.getCPtr(i), i);
  }

  public PacketLogger() {
    this(SLikeNetJNI.new_PacketLogger(), true);
  }

  public void OnReliabilityLayerNotification(String errorMessage, SWIGTYPE_p_unsigned___int32 bitsUsed, SystemAddress remoteSystemAddress, boolean isError) {
    SLikeNetJNI.PacketLogger_OnReliabilityLayerNotification(swigCPtr, this, errorMessage, SWIGTYPE_p_unsigned___int32.getCPtr(bitsUsed), SystemAddress.getCPtr(remoteSystemAddress), remoteSystemAddress, isError);
  }

  public void LogHeader() {
    SLikeNetJNI.PacketLogger_LogHeader(swigCPtr, this);
  }

  public void WriteLog(String str) {
    SLikeNetJNI.PacketLogger_WriteLog(swigCPtr, this, str);
  }

  public void WriteMiscellaneous(String type, String msg) {
    SLikeNetJNI.PacketLogger_WriteMiscellaneous(swigCPtr, this, type, msg);
  }

  public void SetPrintID(boolean print) {
    SLikeNetJNI.PacketLogger_SetPrintID(swigCPtr, this, print);
  }

  public void SetPrintAcks(boolean print) {
    SLikeNetJNI.PacketLogger_SetPrintAcks(swigCPtr, this, print);
  }

  public void SetPrefix(String _prefix) {
    SLikeNetJNI.PacketLogger_SetPrefix(swigCPtr, this, _prefix);
  }

  public void SetSuffix(String _suffix) {
    SLikeNetJNI.PacketLogger_SetSuffix(swigCPtr, this, _suffix);
  }

  public static String BaseIDTOString(short Id) {
    return SLikeNetJNI.PacketLogger_BaseIDTOString(Id);
  }

  public void SetLogDirectMessages(boolean send) {
    SLikeNetJNI.PacketLogger_SetLogDirectMessages(swigCPtr, this, send);
  }

}
