/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class Packet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Packet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Packet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_Packet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSystemAddress(SystemAddress value) {
    SLikeNetJNI.Packet_systemAddress_set(swigCPtr, this, SystemAddress.getCPtr(value), value);
  }

  public SystemAddress getSystemAddress() {
    long cPtr = SLikeNetJNI.Packet_systemAddress_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SystemAddress(cPtr, false);
  }

  public void setGuid(RakNetGUID value) {
    SLikeNetJNI.Packet_guid_set(swigCPtr, this, RakNetGUID.getCPtr(value), value);
  }

  public RakNetGUID getGuid() {
    long cPtr = SLikeNetJNI.Packet_guid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RakNetGUID(cPtr, false);
  }

  public void setLength(long value) {
    SLikeNetJNI.Packet_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return SLikeNetJNI.Packet_length_get(swigCPtr, this);
  }

  public void setBitSize(SWIGTYPE_p_unsigned___int32 value) {
    SLikeNetJNI.Packet_bitSize_set(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned___int32 getBitSize() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.Packet_bitSize_get(swigCPtr, this), true);
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    SLikeNetJNI.Packet_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = SLikeNetJNI.Packet_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDeleteData(boolean value) {
    SLikeNetJNI.Packet_deleteData_set(swigCPtr, this, value);
  }

  public boolean getDeleteData() {
    return SLikeNetJNI.Packet_deleteData_get(swigCPtr, this);
  }

  public void setWasGeneratedLocally(boolean value) {
    SLikeNetJNI.Packet_wasGeneratedLocally_set(swigCPtr, this, value);
  }

  public boolean getWasGeneratedLocally() {
    return SLikeNetJNI.Packet_wasGeneratedLocally_get(swigCPtr, this);
  }

  public ByteArray dataArray() {
    long cPtr = SLikeNetJNI.Packet_dataArray(swigCPtr, this);
    return (cPtr == 0) ? null : new ByteArray(cPtr, false);
  }

  public Packet() {
    this(SLikeNetJNI.new_Packet(), true);
  }

}
