/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class PluginInterface2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PluginInterface2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PluginInterface2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_PluginInterface2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PluginInterface2() {
    this(SLikeNetJNI.new_PluginInterface2(), true);
  }

  public boolean UsesReliabilityLayer() {
    return SLikeNetJNI.PluginInterface2_UsesReliabilityLayer(swigCPtr, this);
  }

  public void OnReliabilityLayerNotification(String errorMessage, SWIGTYPE_p_unsigned___int32 bitsUsed, SystemAddress remoteSystemAddress, boolean isError) {
    SLikeNetJNI.PluginInterface2_OnReliabilityLayerNotification(swigCPtr, this, errorMessage, SWIGTYPE_p_unsigned___int32.getCPtr(bitsUsed), SystemAddress.getCPtr(remoteSystemAddress), remoteSystemAddress, isError);
  }

  public RakPeerInterface GetRakPeerInterface() {
    long cPtr = SLikeNetJNI.PluginInterface2_GetRakPeerInterface(swigCPtr, this);
    return (cPtr == 0) ? null : new RakPeerInterface(cPtr, false);
  }

  public RakNetGUID GetMyGUIDUnified() {
    return new RakNetGUID(SLikeNetJNI.PluginInterface2_GetMyGUIDUnified(swigCPtr, this), true);
  }

  public void SetTCPInterface(SWIGTYPE_p_SLNet__TCPInterface ptr) {
    SLikeNetJNI.PluginInterface2_SetTCPInterface(swigCPtr, this, SWIGTYPE_p_SLNet__TCPInterface.getCPtr(ptr));
  }

}
