/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public final class PublicKeyMode {
  public final static PublicKeyMode PKM_INSECURE_CONNECTION = new PublicKeyMode("PKM_INSECURE_CONNECTION");
  public final static PublicKeyMode PKM_ACCEPT_ANY_PUBLIC_KEY = new PublicKeyMode("PKM_ACCEPT_ANY_PUBLIC_KEY");
  public final static PublicKeyMode PKM_USE_KNOWN_PUBLIC_KEY = new PublicKeyMode("PKM_USE_KNOWN_PUBLIC_KEY");
  public final static PublicKeyMode PKM_USE_TWO_WAY_AUTHENTICATION = new PublicKeyMode("PKM_USE_TWO_WAY_AUTHENTICATION");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PublicKeyMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PublicKeyMode.class + " with value " + swigValue);
  }

  private PublicKeyMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PublicKeyMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PublicKeyMode(String swigName, PublicKeyMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PublicKeyMode[] swigValues = { PKM_INSECURE_CONNECTION, PKM_ACCEPT_ANY_PUBLIC_KEY, PKM_USE_KNOWN_PUBLIC_KEY, PKM_USE_TWO_WAY_AUTHENTICATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

