/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class PublicKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_PublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPublicKeyMode(PublicKeyMode value) {
    SLikeNetJNI.PublicKey_publicKeyMode_set(swigCPtr, this, value.swigValue());
  }

  public PublicKeyMode getPublicKeyMode() {
    return PublicKeyMode.swigToEnum(SLikeNetJNI.PublicKey_publicKeyMode_get(swigCPtr, this));
  }

  public void setRemoteServerPublicKey(String value) {
    SLikeNetJNI.PublicKey_remoteServerPublicKey_set(swigCPtr, this, value);
  }

  public String getRemoteServerPublicKey() {
    return SLikeNetJNI.PublicKey_remoteServerPublicKey_get(swigCPtr, this);
  }

  public void setMyPublicKey(String value) {
    SLikeNetJNI.PublicKey_myPublicKey_set(swigCPtr, this, value);
  }

  public String getMyPublicKey() {
    return SLikeNetJNI.PublicKey_myPublicKey_get(swigCPtr, this);
  }

  public void setMyPrivateKey(String value) {
    SLikeNetJNI.PublicKey_myPrivateKey_set(swigCPtr, this, value);
  }

  public String getMyPrivateKey() {
    return SLikeNetJNI.PublicKey_myPrivateKey_get(swigCPtr, this);
  }

  public PublicKey() {
    this(SLikeNetJNI.new_PublicKey(), true);
  }

}
