/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class PunchthroughConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PunchthroughConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PunchthroughConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_PunchthroughConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PunchthroughConfiguration() {
    this(SLikeNetJNI.new_PunchthroughConfiguration(), true);
  }

  public void setTIME_BETWEEN_PUNCH_ATTEMPTS_INTERNAL(java.math.BigInteger value) {
    SLikeNetJNI.PunchthroughConfiguration_TIME_BETWEEN_PUNCH_ATTEMPTS_INTERNAL_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTIME_BETWEEN_PUNCH_ATTEMPTS_INTERNAL() {
    return SLikeNetJNI.PunchthroughConfiguration_TIME_BETWEEN_PUNCH_ATTEMPTS_INTERNAL_get(swigCPtr, this);
  }

  public void setTIME_BETWEEN_PUNCH_ATTEMPTS_EXTERNAL(java.math.BigInteger value) {
    SLikeNetJNI.PunchthroughConfiguration_TIME_BETWEEN_PUNCH_ATTEMPTS_EXTERNAL_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTIME_BETWEEN_PUNCH_ATTEMPTS_EXTERNAL() {
    return SLikeNetJNI.PunchthroughConfiguration_TIME_BETWEEN_PUNCH_ATTEMPTS_EXTERNAL_get(swigCPtr, this);
  }

  public void setUDP_SENDS_PER_PORT_INTERNAL(int value) {
    SLikeNetJNI.PunchthroughConfiguration_UDP_SENDS_PER_PORT_INTERNAL_set(swigCPtr, this, value);
  }

  public int getUDP_SENDS_PER_PORT_INTERNAL() {
    return SLikeNetJNI.PunchthroughConfiguration_UDP_SENDS_PER_PORT_INTERNAL_get(swigCPtr, this);
  }

  public void setUDP_SENDS_PER_PORT_EXTERNAL(int value) {
    SLikeNetJNI.PunchthroughConfiguration_UDP_SENDS_PER_PORT_EXTERNAL_set(swigCPtr, this, value);
  }

  public int getUDP_SENDS_PER_PORT_EXTERNAL() {
    return SLikeNetJNI.PunchthroughConfiguration_UDP_SENDS_PER_PORT_EXTERNAL_get(swigCPtr, this);
  }

  public void setINTERNAL_IP_WAIT_AFTER_ATTEMPTS(int value) {
    SLikeNetJNI.PunchthroughConfiguration_INTERNAL_IP_WAIT_AFTER_ATTEMPTS_set(swigCPtr, this, value);
  }

  public int getINTERNAL_IP_WAIT_AFTER_ATTEMPTS() {
    return SLikeNetJNI.PunchthroughConfiguration_INTERNAL_IP_WAIT_AFTER_ATTEMPTS_get(swigCPtr, this);
  }

  public void setMAX_PREDICTIVE_PORT_RANGE(int value) {
    SLikeNetJNI.PunchthroughConfiguration_MAX_PREDICTIVE_PORT_RANGE_set(swigCPtr, this, value);
  }

  public int getMAX_PREDICTIVE_PORT_RANGE() {
    return SLikeNetJNI.PunchthroughConfiguration_MAX_PREDICTIVE_PORT_RANGE_get(swigCPtr, this);
  }

  public void setEXTERNAL_IP_WAIT_AFTER_FIRST_TTL(int value) {
    SLikeNetJNI.PunchthroughConfiguration_EXTERNAL_IP_WAIT_AFTER_FIRST_TTL_set(swigCPtr, this, value);
  }

  public int getEXTERNAL_IP_WAIT_AFTER_FIRST_TTL() {
    return SLikeNetJNI.PunchthroughConfiguration_EXTERNAL_IP_WAIT_AFTER_FIRST_TTL_get(swigCPtr, this);
  }

  public void setEXTERNAL_IP_WAIT_BETWEEN_PORTS(int value) {
    SLikeNetJNI.PunchthroughConfiguration_EXTERNAL_IP_WAIT_BETWEEN_PORTS_set(swigCPtr, this, value);
  }

  public int getEXTERNAL_IP_WAIT_BETWEEN_PORTS() {
    return SLikeNetJNI.PunchthroughConfiguration_EXTERNAL_IP_WAIT_BETWEEN_PORTS_get(swigCPtr, this);
  }

  public void setEXTERNAL_IP_WAIT_AFTER_ALL_ATTEMPTS(int value) {
    SLikeNetJNI.PunchthroughConfiguration_EXTERNAL_IP_WAIT_AFTER_ALL_ATTEMPTS_set(swigCPtr, this, value);
  }

  public int getEXTERNAL_IP_WAIT_AFTER_ALL_ATTEMPTS() {
    return SLikeNetJNI.PunchthroughConfiguration_EXTERNAL_IP_WAIT_AFTER_ALL_ATTEMPTS_get(swigCPtr, this);
  }

  public void setMAXIMUM_NUMBER_OF_INTERNAL_IDS_TO_CHECK(int value) {
    SLikeNetJNI.PunchthroughConfiguration_MAXIMUM_NUMBER_OF_INTERNAL_IDS_TO_CHECK_set(swigCPtr, this, value);
  }

  public int getMAXIMUM_NUMBER_OF_INTERNAL_IDS_TO_CHECK() {
    return SLikeNetJNI.PunchthroughConfiguration_MAXIMUM_NUMBER_OF_INTERNAL_IDS_TO_CHECK_get(swigCPtr, this);
  }

  public void setRetryOnFailure(boolean value) {
    SLikeNetJNI.PunchthroughConfiguration_retryOnFailure_set(swigCPtr, this, value);
  }

  public boolean getRetryOnFailure() {
    return SLikeNetJNI.PunchthroughConfiguration_retryOnFailure_get(swigCPtr, this);
  }

}
