/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetListSortQuery {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetListSortQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetListSortQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetListSortQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   

  public RakNetListSortQuery() {
    this(SLikeNetJNI.new_RakNetListSortQuery__SWIG_0(), true);
  }

  public RakNetListSortQuery(RakNetListSortQuery original_copy) {
    this(SLikeNetJNI.new_RakNetListSortQuery__SWIG_1(RakNetListSortQuery.getCPtr(original_copy), original_copy), true);
  }

  public SWIGTYPE_p_SortQuery Get(long position) {
    return new SWIGTYPE_p_SortQuery(SLikeNetJNI.RakNetListSortQuery_Get(swigCPtr, this, position), false);
  }

  public void Push(SWIGTYPE_p_SortQuery input, String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Push(swigCPtr, this, SWIGTYPE_p_SortQuery.getCPtr(input), file, line);
  }

  public SWIGTYPE_p_SortQuery Pop() {
    return new SWIGTYPE_p_SortQuery(SLikeNetJNI.RakNetListSortQuery_Pop(swigCPtr, this), false);
  }

  public void Insert(SWIGTYPE_p_SortQuery input, long position, String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Insert__SWIG_0(swigCPtr, this, SWIGTYPE_p_SortQuery.getCPtr(input), position, file, line);
  }

  public void Insert(SWIGTYPE_p_SortQuery input, String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Insert__SWIG_1(swigCPtr, this, SWIGTYPE_p_SortQuery.getCPtr(input), file, line);
  }

  public void Replace(SWIGTYPE_p_SortQuery input, SWIGTYPE_p_SortQuery filler, long position, String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Replace__SWIG_0(swigCPtr, this, SWIGTYPE_p_SortQuery.getCPtr(input), SWIGTYPE_p_SortQuery.getCPtr(filler), position, file, line);
  }

  public void Replace(SWIGTYPE_p_SortQuery input) {
    SLikeNetJNI.RakNetListSortQuery_Replace__SWIG_1(swigCPtr, this, SWIGTYPE_p_SortQuery.getCPtr(input));
  }

  public void RemoveAtIndex(long position) {
    SLikeNetJNI.RakNetListSortQuery_RemoveAtIndex(swigCPtr, this, position);
  }

  public void RemoveAtIndexFast(long position) {
    SLikeNetJNI.RakNetListSortQuery_RemoveAtIndexFast(swigCPtr, this, position);
  }

  public void RemoveFromEnd(long num) {
    SLikeNetJNI.RakNetListSortQuery_RemoveFromEnd__SWIG_0(swigCPtr, this, num);
  }

  public void RemoveFromEnd() {
    SLikeNetJNI.RakNetListSortQuery_RemoveFromEnd__SWIG_1(swigCPtr, this);
  }

  public long Size() {
    return SLikeNetJNI.RakNetListSortQuery_Size(swigCPtr, this);
  }

  public void Clear(boolean doNotDeallocateSmallBlocks, String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Clear(swigCPtr, this, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(long countNeeded, String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Preallocate(swigCPtr, this, countNeeded, file, line);
  }

  public void Compress(String file, long line) {
    SLikeNetJNI.RakNetListSortQuery_Compress(swigCPtr, this, file, line);
  }

}
