/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetListRakString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetListRakString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetListRakString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetListRakString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   

  public RakNetListRakString() {
    this(SLikeNetJNI.new_RakNetListRakString__SWIG_0(), true);
  }

  public RakNetListRakString(RakNetListRakString original_copy) {
    this(SLikeNetJNI.new_RakNetListRakString__SWIG_1(RakNetListRakString.getCPtr(original_copy), original_copy), true);
  }

  public RakString Get(long position) {
    return new RakString(SLikeNetJNI.RakNetListRakString_Get(swigCPtr, this, position), false);
  }

  public void Push(RakString input, String file, long line) {
    SLikeNetJNI.RakNetListRakString_Push(swigCPtr, this, RakString.getCPtr(input), input, file, line);
  }

  public RakString Pop() {
    return new RakString(SLikeNetJNI.RakNetListRakString_Pop(swigCPtr, this), false);
  }

  public void Insert(RakString input, long position, String file, long line) {
    SLikeNetJNI.RakNetListRakString_Insert__SWIG_0(swigCPtr, this, RakString.getCPtr(input), input, position, file, line);
  }

  public void Insert(RakString input, String file, long line) {
    SLikeNetJNI.RakNetListRakString_Insert__SWIG_1(swigCPtr, this, RakString.getCPtr(input), input, file, line);
  }

  public void Replace(RakString input, RakString filler, long position, String file, long line) {
    SLikeNetJNI.RakNetListRakString_Replace__SWIG_0(swigCPtr, this, RakString.getCPtr(input), input, RakString.getCPtr(filler), filler, position, file, line);
  }

  public void Replace(RakString input) {
    SLikeNetJNI.RakNetListRakString_Replace__SWIG_1(swigCPtr, this, RakString.getCPtr(input), input);
  }

  public void RemoveAtIndex(long position) {
    SLikeNetJNI.RakNetListRakString_RemoveAtIndex(swigCPtr, this, position);
  }

  public void RemoveAtIndexFast(long position) {
    SLikeNetJNI.RakNetListRakString_RemoveAtIndexFast(swigCPtr, this, position);
  }

  public void RemoveFromEnd(long num) {
    SLikeNetJNI.RakNetListRakString_RemoveFromEnd__SWIG_0(swigCPtr, this, num);
  }

  public void RemoveFromEnd() {
    SLikeNetJNI.RakNetListRakString_RemoveFromEnd__SWIG_1(swigCPtr, this);
  }

  public long GetIndexOf(RakString input) {
    return SLikeNetJNI.RakNetListRakString_GetIndexOf(swigCPtr, this, RakString.getCPtr(input), input);
  }

  public long Size() {
    return SLikeNetJNI.RakNetListRakString_Size(swigCPtr, this);
  }

  public void Clear(boolean doNotDeallocateSmallBlocks, String file, long line) {
    SLikeNetJNI.RakNetListRakString_Clear(swigCPtr, this, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(long countNeeded, String file, long line) {
    SLikeNetJNI.RakNetListRakString_Preallocate(swigCPtr, this, countNeeded, file, line);
  }

  public void Compress(String file, long line) {
    SLikeNetJNI.RakNetListRakString_Compress(swigCPtr, this, file, line);
  }

}
