/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetListFilterQuery {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetListFilterQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetListFilterQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetListFilterQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   

  public RakNetListFilterQuery() {
    this(SLikeNetJNI.new_RakNetListFilterQuery__SWIG_0(), true);
  }

  public RakNetListFilterQuery(RakNetListFilterQuery original_copy) {
    this(SLikeNetJNI.new_RakNetListFilterQuery__SWIG_1(RakNetListFilterQuery.getCPtr(original_copy), original_copy), true);
  }

  public SWIGTYPE_p_FilterQuery Get(long position) {
    return new SWIGTYPE_p_FilterQuery(SLikeNetJNI.RakNetListFilterQuery_Get(swigCPtr, this, position), false);
  }

  public void Push(SWIGTYPE_p_FilterQuery input, String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Push(swigCPtr, this, SWIGTYPE_p_FilterQuery.getCPtr(input), file, line);
  }

  public SWIGTYPE_p_FilterQuery Pop() {
    return new SWIGTYPE_p_FilterQuery(SLikeNetJNI.RakNetListFilterQuery_Pop(swigCPtr, this), false);
  }

  public void Insert(SWIGTYPE_p_FilterQuery input, long position, String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Insert__SWIG_0(swigCPtr, this, SWIGTYPE_p_FilterQuery.getCPtr(input), position, file, line);
  }

  public void Insert(SWIGTYPE_p_FilterQuery input, String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Insert__SWIG_1(swigCPtr, this, SWIGTYPE_p_FilterQuery.getCPtr(input), file, line);
  }

  public void Replace(SWIGTYPE_p_FilterQuery input, SWIGTYPE_p_FilterQuery filler, long position, String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Replace__SWIG_0(swigCPtr, this, SWIGTYPE_p_FilterQuery.getCPtr(input), SWIGTYPE_p_FilterQuery.getCPtr(filler), position, file, line);
  }

  public void Replace(SWIGTYPE_p_FilterQuery input) {
    SLikeNetJNI.RakNetListFilterQuery_Replace__SWIG_1(swigCPtr, this, SWIGTYPE_p_FilterQuery.getCPtr(input));
  }

  public void RemoveAtIndex(long position) {
    SLikeNetJNI.RakNetListFilterQuery_RemoveAtIndex(swigCPtr, this, position);
  }

  public void RemoveAtIndexFast(long position) {
    SLikeNetJNI.RakNetListFilterQuery_RemoveAtIndexFast(swigCPtr, this, position);
  }

  public void RemoveFromEnd(long num) {
    SLikeNetJNI.RakNetListFilterQuery_RemoveFromEnd__SWIG_0(swigCPtr, this, num);
  }

  public void RemoveFromEnd() {
    SLikeNetJNI.RakNetListFilterQuery_RemoveFromEnd__SWIG_1(swigCPtr, this);
  }

  public long Size() {
    return SLikeNetJNI.RakNetListFilterQuery_Size(swigCPtr, this);
  }

  public void Clear(boolean doNotDeallocateSmallBlocks, String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Clear(swigCPtr, this, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(long countNeeded, String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Preallocate(swigCPtr, this, countNeeded, file, line);
  }

  public void Compress(String file, long line) {
    SLikeNetJNI.RakNetListFilterQuery_Compress(swigCPtr, this, file, line);
  }

}
