/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetListRakNetGUID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetListRakNetGUID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetListRakNetGUID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetListRakNetGUID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   

  public RakNetListRakNetGUID() {
    this(SLikeNetJNI.new_RakNetListRakNetGUID__SWIG_0(), true);
  }

  public RakNetListRakNetGUID(RakNetListRakNetGUID original_copy) {
    this(SLikeNetJNI.new_RakNetListRakNetGUID__SWIG_1(RakNetListRakNetGUID.getCPtr(original_copy), original_copy), true);
  }

  public RakNetGUID Get(long position) {
    return new RakNetGUID(SLikeNetJNI.RakNetListRakNetGUID_Get(swigCPtr, this, position), false);
  }

  public void Push(RakNetGUID input, String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Push(swigCPtr, this, RakNetGUID.getCPtr(input), input, file, line);
  }

  public RakNetGUID Pop() {
    return new RakNetGUID(SLikeNetJNI.RakNetListRakNetGUID_Pop(swigCPtr, this), false);
  }

  public void Insert(RakNetGUID input, long position, String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Insert__SWIG_0(swigCPtr, this, RakNetGUID.getCPtr(input), input, position, file, line);
  }

  public void Insert(RakNetGUID input, String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Insert__SWIG_1(swigCPtr, this, RakNetGUID.getCPtr(input), input, file, line);
  }

  public void Replace(RakNetGUID input, RakNetGUID filler, long position, String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Replace__SWIG_0(swigCPtr, this, RakNetGUID.getCPtr(input), input, RakNetGUID.getCPtr(filler), filler, position, file, line);
  }

  public void Replace(RakNetGUID input) {
    SLikeNetJNI.RakNetListRakNetGUID_Replace__SWIG_1(swigCPtr, this, RakNetGUID.getCPtr(input), input);
  }

  public void RemoveAtIndex(long position) {
    SLikeNetJNI.RakNetListRakNetGUID_RemoveAtIndex(swigCPtr, this, position);
  }

  public void RemoveAtIndexFast(long position) {
    SLikeNetJNI.RakNetListRakNetGUID_RemoveAtIndexFast(swigCPtr, this, position);
  }

  public void RemoveFromEnd(long num) {
    SLikeNetJNI.RakNetListRakNetGUID_RemoveFromEnd__SWIG_0(swigCPtr, this, num);
  }

  public void RemoveFromEnd() {
    SLikeNetJNI.RakNetListRakNetGUID_RemoveFromEnd__SWIG_1(swigCPtr, this);
  }

  public long GetIndexOf(RakNetGUID input) {
    return SLikeNetJNI.RakNetListRakNetGUID_GetIndexOf(swigCPtr, this, RakNetGUID.getCPtr(input), input);
  }

  public long Size() {
    return SLikeNetJNI.RakNetListRakNetGUID_Size(swigCPtr, this);
  }

  public void Clear(boolean doNotDeallocateSmallBlocks, String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Clear(swigCPtr, this, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(long countNeeded, String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Preallocate(swigCPtr, this, countNeeded, file, line);
  }

  public void Compress(String file, long line) {
    SLikeNetJNI.RakNetListRakNetGUID_Compress(swigCPtr, this, file, line);
  }

}
