/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetBPlusTreeRow {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetBPlusTreeRow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetBPlusTreeRow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetBPlusTreeRow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class ReturnAction {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected ReturnAction(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(ReturnAction obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SLikeNetJNI.delete_RakNetBPlusTreeRow_ReturnAction(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setKey1(long value) {
      SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_key1_set(swigCPtr, this, value);
    }
  
    public long getKey1() {
      return SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_key1_get(swigCPtr, this);
    }
  
    public void setKey2(long value) {
      SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_key2_set(swigCPtr, this, value);
    }
  
    public long getKey2() {
      return SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_key2_get(swigCPtr, this);
    }
  
    public void setAction(int value) {
      SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_action_set(swigCPtr, this, value);
    }
  
    public int getAction() {
      return SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_action_get(swigCPtr, this);
    }
  
    public ReturnAction() {
      this(SLikeNetJNI.new_RakNetBPlusTreeRow_ReturnAction(), true);
    }
  
    public final static int NO_ACTION = SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_NO_ACTION_get();
    public final static int REPLACE_KEY1_WITH_KEY2 = SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_REPLACE_KEY1_WITH_KEY2_get();
    public final static int PUSH_KEY_TO_PARENT = SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_PUSH_KEY_TO_PARENT_get();
    public final static int SET_BRANCH_KEY = SLikeNetJNI.RakNetBPlusTreeRow_ReturnAction_SET_BRANCH_KEY_get();
  
  }

  public RakNetBPlusTreeRow() {
    this(SLikeNetJNI.new_RakNetBPlusTreeRow(), true);
  }

  public void SetPoolPageSize(int size) {
    SLikeNetJNI.RakNetBPlusTreeRow_SetPoolPageSize(swigCPtr, this, size);
  }

  public boolean Insert(long key, Table.Row data) {
    return SLikeNetJNI.RakNetBPlusTreeRow_Insert(swigCPtr, this, key, Table.Row.getCPtr(data), data);
  }

  public void Clear() {
    SLikeNetJNI.RakNetBPlusTreeRow_Clear(swigCPtr, this);
  }

  public long Size() {
    return SLikeNetJNI.RakNetBPlusTreeRow_Size(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return SLikeNetJNI.RakNetBPlusTreeRow_IsEmpty(swigCPtr, this);
  }

  public RakNetPageRow GetListHead() {
    long cPtr = SLikeNetJNI.RakNetBPlusTreeRow_GetListHead(swigCPtr, this);
    return (cPtr == 0) ? null : new RakNetPageRow(cPtr, false);
  }

  public Table.Row GetDataHead() {
    long cPtr = SLikeNetJNI.RakNetBPlusTreeRow_GetDataHead(swigCPtr, this);
    return (cPtr == 0) ? null : new Table.Row(cPtr, false);
  }

  public void PrintLeaves() {
    SLikeNetJNI.RakNetBPlusTreeRow_PrintLeaves(swigCPtr, this);
  }

  public void PrintGraph() {
    SLikeNetJNI.RakNetBPlusTreeRow_PrintGraph(swigCPtr, this);
  }

}
