/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetListSystemAddress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetListSystemAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetListSystemAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetListSystemAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   

  public RakNetListSystemAddress() {
    this(SLikeNetJNI.new_RakNetListSystemAddress__SWIG_0(), true);
  }

  public RakNetListSystemAddress(RakNetListSystemAddress original_copy) {
    this(SLikeNetJNI.new_RakNetListSystemAddress__SWIG_1(RakNetListSystemAddress.getCPtr(original_copy), original_copy), true);
  }

  public SystemAddress Get(long position) {
    return new SystemAddress(SLikeNetJNI.RakNetListSystemAddress_Get(swigCPtr, this, position), false);
  }

  public void Push(SystemAddress input, String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Push(swigCPtr, this, SystemAddress.getCPtr(input), input, file, line);
  }

  public SystemAddress Pop() {
    return new SystemAddress(SLikeNetJNI.RakNetListSystemAddress_Pop(swigCPtr, this), false);
  }

  public void Insert(SystemAddress input, long position, String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Insert__SWIG_0(swigCPtr, this, SystemAddress.getCPtr(input), input, position, file, line);
  }

  public void Insert(SystemAddress input, String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Insert__SWIG_1(swigCPtr, this, SystemAddress.getCPtr(input), input, file, line);
  }

  public void Replace(SystemAddress input, SystemAddress filler, long position, String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Replace__SWIG_0(swigCPtr, this, SystemAddress.getCPtr(input), input, SystemAddress.getCPtr(filler), filler, position, file, line);
  }

  public void Replace(SystemAddress input) {
    SLikeNetJNI.RakNetListSystemAddress_Replace__SWIG_1(swigCPtr, this, SystemAddress.getCPtr(input), input);
  }

  public void RemoveAtIndex(long position) {
    SLikeNetJNI.RakNetListSystemAddress_RemoveAtIndex(swigCPtr, this, position);
  }

  public void RemoveAtIndexFast(long position) {
    SLikeNetJNI.RakNetListSystemAddress_RemoveAtIndexFast(swigCPtr, this, position);
  }

  public void RemoveFromEnd(long num) {
    SLikeNetJNI.RakNetListSystemAddress_RemoveFromEnd__SWIG_0(swigCPtr, this, num);
  }

  public void RemoveFromEnd() {
    SLikeNetJNI.RakNetListSystemAddress_RemoveFromEnd__SWIG_1(swigCPtr, this);
  }

  public long GetIndexOf(SystemAddress input) {
    return SLikeNetJNI.RakNetListSystemAddress_GetIndexOf(swigCPtr, this, SystemAddress.getCPtr(input), input);
  }

  public long Size() {
    return SLikeNetJNI.RakNetListSystemAddress_Size(swigCPtr, this);
  }

  public void Clear(boolean doNotDeallocateSmallBlocks, String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Clear(swigCPtr, this, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(long countNeeded, String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Preallocate(swigCPtr, this, countNeeded, file, line);
  }

  public void Compress(String file, long line) {
    SLikeNetJNI.RakNetListSystemAddress_Compress(swigCPtr, this, file, line);
  }

}
