/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetStatistics {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetStatistics(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValueOverLastSecond(SWIGTYPE_p_unsigned_long_long value) {
    SLikeNetJNI.RakNetStatistics_valueOverLastSecond_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getValueOverLastSecond() {
    long cPtr = SLikeNetJNI.RakNetStatistics_valueOverLastSecond_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setRunningTotal(SWIGTYPE_p_unsigned_long_long value) {
    SLikeNetJNI.RakNetStatistics_runningTotal_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getRunningTotal() {
    long cPtr = SLikeNetJNI.RakNetStatistics_runningTotal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setConnectionStartTime(java.math.BigInteger value) {
    SLikeNetJNI.RakNetStatistics_connectionStartTime_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getConnectionStartTime() {
    return SLikeNetJNI.RakNetStatistics_connectionStartTime_get(swigCPtr, this);
  }

  public void setIsLimitedByCongestionControl(boolean value) {
    SLikeNetJNI.RakNetStatistics_isLimitedByCongestionControl_set(swigCPtr, this, value);
  }

  public boolean getIsLimitedByCongestionControl() {
    return SLikeNetJNI.RakNetStatistics_isLimitedByCongestionControl_get(swigCPtr, this);
  }

  public void setBPSLimitByCongestionControl(java.math.BigInteger value) {
    SLikeNetJNI.RakNetStatistics_BPSLimitByCongestionControl_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBPSLimitByCongestionControl() {
    return SLikeNetJNI.RakNetStatistics_BPSLimitByCongestionControl_get(swigCPtr, this);
  }

  public void setIsLimitedByOutgoingBandwidthLimit(boolean value) {
    SLikeNetJNI.RakNetStatistics_isLimitedByOutgoingBandwidthLimit_set(swigCPtr, this, value);
  }

  public boolean getIsLimitedByOutgoingBandwidthLimit() {
    return SLikeNetJNI.RakNetStatistics_isLimitedByOutgoingBandwidthLimit_get(swigCPtr, this);
  }

  public void setBPSLimitByOutgoingBandwidthLimit(java.math.BigInteger value) {
    SLikeNetJNI.RakNetStatistics_BPSLimitByOutgoingBandwidthLimit_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBPSLimitByOutgoingBandwidthLimit() {
    return SLikeNetJNI.RakNetStatistics_BPSLimitByOutgoingBandwidthLimit_get(swigCPtr, this);
  }

  public void setMessageInSendBuffer(long[] value) {
    SLikeNetJNI.RakNetStatistics_messageInSendBuffer_set(swigCPtr, this, value);
  }

  public long[] getMessageInSendBuffer() {
    return SLikeNetJNI.RakNetStatistics_messageInSendBuffer_get(swigCPtr, this);
  }

  public void setBytesInSendBuffer(double[] value) {
    SLikeNetJNI.RakNetStatistics_bytesInSendBuffer_set(swigCPtr, this, value);
  }

  public double[] getBytesInSendBuffer() {
    return SLikeNetJNI.RakNetStatistics_bytesInSendBuffer_get(swigCPtr, this);
  }

  public void setMessagesInResendBuffer(long value) {
    SLikeNetJNI.RakNetStatistics_messagesInResendBuffer_set(swigCPtr, this, value);
  }

  public long getMessagesInResendBuffer() {
    return SLikeNetJNI.RakNetStatistics_messagesInResendBuffer_get(swigCPtr, this);
  }

  public void setBytesInResendBuffer(java.math.BigInteger value) {
    SLikeNetJNI.RakNetStatistics_bytesInResendBuffer_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBytesInResendBuffer() {
    return SLikeNetJNI.RakNetStatistics_bytesInResendBuffer_get(swigCPtr, this);
  }

  public void setPacketlossLastSecond(float value) {
    SLikeNetJNI.RakNetStatistics_packetlossLastSecond_set(swigCPtr, this, value);
  }

  public float getPacketlossLastSecond() {
    return SLikeNetJNI.RakNetStatistics_packetlossLastSecond_get(swigCPtr, this);
  }

  public void setPacketlossTotal(float value) {
    SLikeNetJNI.RakNetStatistics_packetlossTotal_set(swigCPtr, this, value);
  }

  public float getPacketlossTotal() {
    return SLikeNetJNI.RakNetStatistics_packetlossTotal_get(swigCPtr, this);
  }

  public RakNetStatistics() {
    this(SLikeNetJNI.new_RakNetStatistics(), true);
  }

}
