/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetGUID {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetGUID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetGUID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetGUID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RakNetGUID() {
    this(SLikeNetJNI.new_RakNetGUID__SWIG_0(), true);
  }

  public RakNetGUID(java.math.BigInteger _g) {
    this(SLikeNetJNI.new_RakNetGUID__SWIG_1(_g), true);
  }

  public void setG(java.math.BigInteger value) {
    SLikeNetJNI.RakNetGUID_g_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getG() {
    return SLikeNetJNI.RakNetGUID_g_get(swigCPtr, this);
  }

  public String ToString() {
    return SLikeNetJNI.RakNetGUID_ToString__SWIG_0(swigCPtr, this);
  }

  public void ToString(String dest, long destSize) {
    SLikeNetJNI.RakNetGUID_ToString__SWIG_1(swigCPtr, this, dest, destSize);
  }

  public boolean FromString(String source) {
    return SLikeNetJNI.RakNetGUID_FromString(swigCPtr, this, source);
  }

  public static long ToUint32(RakNetGUID g) {
    return SLikeNetJNI.RakNetGUID_ToUint32(RakNetGUID.getCPtr(g), g);
  }

  public void setSystemIndex(int value) {
    SLikeNetJNI.RakNetGUID_systemIndex_set(swigCPtr, this, value);
  }

  public int getSystemIndex() {
    return SLikeNetJNI.RakNetGUID_systemIndex_get(swigCPtr, this);
  }

  public static int size() {
    return SLikeNetJNI.RakNetGUID_size();
  }

}
