/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RakNetListCell {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RakNetListCell(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RakNetListCell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RakNetListCell(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   

  public RakNetListCell() {
    this(SLikeNetJNI.new_RakNetListCell__SWIG_0(), true);
  }

  public RakNetListCell(RakNetListCell original_copy) {
    this(SLikeNetJNI.new_RakNetListCell__SWIG_1(RakNetListCell.getCPtr(original_copy), original_copy), true);
  }

  public SWIGTYPE_p_Cell Get(long position) {
    return new SWIGTYPE_p_Cell(SLikeNetJNI.RakNetListCell_Get(swigCPtr, this, position), false);
  }

  public void Push(SWIGTYPE_p_Cell input, String file, long line) {
    SLikeNetJNI.RakNetListCell_Push(swigCPtr, this, SWIGTYPE_p_Cell.getCPtr(input), file, line);
  }

  public SWIGTYPE_p_Cell Pop() {
    return new SWIGTYPE_p_Cell(SLikeNetJNI.RakNetListCell_Pop(swigCPtr, this), false);
  }

  public void Insert(SWIGTYPE_p_Cell input, long position, String file, long line) {
    SLikeNetJNI.RakNetListCell_Insert__SWIG_0(swigCPtr, this, SWIGTYPE_p_Cell.getCPtr(input), position, file, line);
  }

  public void Insert(SWIGTYPE_p_Cell input, String file, long line) {
    SLikeNetJNI.RakNetListCell_Insert__SWIG_1(swigCPtr, this, SWIGTYPE_p_Cell.getCPtr(input), file, line);
  }

  public void Replace(SWIGTYPE_p_Cell input, SWIGTYPE_p_Cell filler, long position, String file, long line) {
    SLikeNetJNI.RakNetListCell_Replace__SWIG_0(swigCPtr, this, SWIGTYPE_p_Cell.getCPtr(input), SWIGTYPE_p_Cell.getCPtr(filler), position, file, line);
  }

  public void Replace(SWIGTYPE_p_Cell input) {
    SLikeNetJNI.RakNetListCell_Replace__SWIG_1(swigCPtr, this, SWIGTYPE_p_Cell.getCPtr(input));
  }

  public void RemoveAtIndex(long position) {
    SLikeNetJNI.RakNetListCell_RemoveAtIndex(swigCPtr, this, position);
  }

  public void RemoveAtIndexFast(long position) {
    SLikeNetJNI.RakNetListCell_RemoveAtIndexFast(swigCPtr, this, position);
  }

  public void RemoveFromEnd(long num) {
    SLikeNetJNI.RakNetListCell_RemoveFromEnd__SWIG_0(swigCPtr, this, num);
  }

  public void RemoveFromEnd() {
    SLikeNetJNI.RakNetListCell_RemoveFromEnd__SWIG_1(swigCPtr, this);
  }

  public long Size() {
    return SLikeNetJNI.RakNetListCell_Size(swigCPtr, this);
  }

  public void Clear(boolean doNotDeallocateSmallBlocks, String file, long line) {
    SLikeNetJNI.RakNetListCell_Clear(swigCPtr, this, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(long countNeeded, String file, long line) {
    SLikeNetJNI.RakNetListCell_Preallocate(swigCPtr, this, countNeeded, file, line);
  }

  public void Compress(String file, long line) {
    SLikeNetJNI.RakNetListCell_Compress(swigCPtr, this, file, line);
  }

}
