/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public final class ReadyEventSystemStatus {
  public final static ReadyEventSystemStatus RES_NOT_WAITING = new ReadyEventSystemStatus("RES_NOT_WAITING");
  public final static ReadyEventSystemStatus RES_WAITING = new ReadyEventSystemStatus("RES_WAITING");
  public final static ReadyEventSystemStatus RES_READY = new ReadyEventSystemStatus("RES_READY");
  public final static ReadyEventSystemStatus RES_ALL_READY = new ReadyEventSystemStatus("RES_ALL_READY");
  public final static ReadyEventSystemStatus RES_UNKNOWN_EVENT = new ReadyEventSystemStatus("RES_UNKNOWN_EVENT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ReadyEventSystemStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ReadyEventSystemStatus.class + " with value " + swigValue);
  }

  private ReadyEventSystemStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ReadyEventSystemStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ReadyEventSystemStatus(String swigName, ReadyEventSystemStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ReadyEventSystemStatus[] swigValues = { RES_NOT_WAITING, RES_WAITING, RES_READY, RES_ALL_READY, RES_UNKNOWN_EVENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

