/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class RemoteSystemIndex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RemoteSystemIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RemoteSystemIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_RemoteSystemIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(long value) {
    SLikeNetJNI.RemoteSystemIndex_index_set(swigCPtr, this, value);
  }

  public long getIndex() {
    return SLikeNetJNI.RemoteSystemIndex_index_get(swigCPtr, this);
  }

  public void setNext(RemoteSystemIndex value) {
    SLikeNetJNI.RemoteSystemIndex_next_set(swigCPtr, this, RemoteSystemIndex.getCPtr(value), value);
  }

  public RemoteSystemIndex getNext() {
    long cPtr = SLikeNetJNI.RemoteSystemIndex_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RemoteSystemIndex(cPtr, false);
  }

  public RemoteSystemIndex() {
    this(SLikeNetJNI.new_RemoteSystemIndex(), true);
  }

}
