/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public final class RNSPerSecondMetrics {
  public final static RNSPerSecondMetrics USER_MESSAGE_BYTES_PUSHED = new RNSPerSecondMetrics("USER_MESSAGE_BYTES_PUSHED");
  public final static RNSPerSecondMetrics USER_MESSAGE_BYTES_SENT = new RNSPerSecondMetrics("USER_MESSAGE_BYTES_SENT");
  public final static RNSPerSecondMetrics USER_MESSAGE_BYTES_RESENT = new RNSPerSecondMetrics("USER_MESSAGE_BYTES_RESENT");
  public final static RNSPerSecondMetrics USER_MESSAGE_BYTES_RECEIVED_PROCESSED = new RNSPerSecondMetrics("USER_MESSAGE_BYTES_RECEIVED_PROCESSED");
  public final static RNSPerSecondMetrics USER_MESSAGE_BYTES_RECEIVED_IGNORED = new RNSPerSecondMetrics("USER_MESSAGE_BYTES_RECEIVED_IGNORED");
  public final static RNSPerSecondMetrics ACTUAL_BYTES_SENT = new RNSPerSecondMetrics("ACTUAL_BYTES_SENT");
  public final static RNSPerSecondMetrics ACTUAL_BYTES_RECEIVED = new RNSPerSecondMetrics("ACTUAL_BYTES_RECEIVED");
  public final static RNSPerSecondMetrics RNS_PER_SECOND_METRICS_COUNT = new RNSPerSecondMetrics("RNS_PER_SECOND_METRICS_COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RNSPerSecondMetrics swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RNSPerSecondMetrics.class + " with value " + swigValue);
  }

  private RNSPerSecondMetrics(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RNSPerSecondMetrics(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RNSPerSecondMetrics(String swigName, RNSPerSecondMetrics swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RNSPerSecondMetrics[] swigValues = { USER_MESSAGE_BYTES_PUSHED, USER_MESSAGE_BYTES_SENT, USER_MESSAGE_BYTES_RESENT, USER_MESSAGE_BYTES_RECEIVED_PROCESSED, USER_MESSAGE_BYTES_RECEIVED_IGNORED, ACTUAL_BYTES_SENT, ACTUAL_BYTES_RECEIVED, RNS_PER_SECOND_METRICS_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

