/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class Router2DebugInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Router2DebugInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Router2DebugInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_Router2DebugInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Router2DebugInterface() {
    this(SLikeNetJNI.new_Router2DebugInterface(), true);
  }

  public void ShowFailure(String message) {
    SLikeNetJNI.Router2DebugInterface_ShowFailure(swigCPtr, this, message);
  }

  public void ShowDiagnostic(String message) {
    SLikeNetJNI.Router2DebugInterface_ShowDiagnostic(swigCPtr, this, message);
  }

}
