/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public interface SLikeNetConstants {
  public final static int __GET_TIME_64BIT = SLikeNetJNI.__GET_TIME_64BIT_get();
  public final static int MAX_ALLOCA_STACK_ALLOCATION = SLikeNetJNI.MAX_ALLOCA_STACK_ALLOCATION_get();
  public final static int _USE_RAK_MEMORY_OVERRIDE = SLikeNetJNI._USE_RAK_MEMORY_OVERRIDE_get();
  public final static int OPEN_SSL_CLIENT_SUPPORT = SLikeNetJNI.OPEN_SSL_CLIENT_SUPPORT_get();
  public final static int BITSTREAM_STACK_ALLOCATION_SIZE = SLikeNetJNI.BITSTREAM_STACK_ALLOCATION_SIZE_get();
  public final static int MAXIMUM_NUMBER_OF_INTERNAL_IDS = SLikeNetJNI.MAXIMUM_NUMBER_OF_INTERNAL_IDS_get();
  public final static int DATAGRAM_MESSAGE_ID_ARRAY_LENGTH = SLikeNetJNI.DATAGRAM_MESSAGE_ID_ARRAY_LENGTH_get();
  public final static int RESEND_BUFFER_ARRAY_LENGTH = SLikeNetJNI.RESEND_BUFFER_ARRAY_LENGTH_get();
  public final static int RESEND_BUFFER_ARRAY_MASK = SLikeNetJNI.RESEND_BUFFER_ARRAY_MASK_get();
  public final static int GET_TIME_SPIKE_LIMIT = SLikeNetJNI.GET_TIME_SPIKE_LIMIT_get();
  public final static int USE_SLIDING_WINDOW_CONGESTION_CONTROL = SLikeNetJNI.USE_SLIDING_WINDOW_CONGESTION_CONTROL_get();
  public final static int PREALLOCATE_LARGE_MESSAGES = SLikeNetJNI.PREALLOCATE_LARGE_MESSAGES_get();
  public final static int RAKNET_SUPPORT_IPV6 = SLikeNetJNI.RAKNET_SUPPORT_IPV6_get();
  public final static int RAKSTRING_TYPE_IS_UNICODE = SLikeNetJNI.RAKSTRING_TYPE_IS_UNICODE_get();
  public final static int RPC4_GLOBAL_REGISTRATION_MAX_FUNCTIONS = SLikeNetJNI.RPC4_GLOBAL_REGISTRATION_MAX_FUNCTIONS_get();
  public final static int RPC4_GLOBAL_REGISTRATION_MAX_FUNCTION_NAME_LENGTH = SLikeNetJNI.RPC4_GLOBAL_REGISTRATION_MAX_FUNCTION_NAME_LENGTH_get();
  public final static int XBOX_BYPASS_SECURITY = SLikeNetJNI.XBOX_BYPASS_SECURITY_get();
  public final static int BUFFERED_PACKETS_PAGE_SIZE = SLikeNetJNI.BUFFERED_PACKETS_PAGE_SIZE_get();
  public final static int INTERNAL_PACKET_PAGE_SIZE = SLikeNetJNI.INTERNAL_PACKET_PAGE_SIZE_get();
  public final static int RAKPEER_USER_THREADED = SLikeNetJNI.RAKPEER_USER_THREADED_get();
  public final static int USE_ALLOCA = SLikeNetJNI.USE_ALLOCA_get();
  public final static int SLNET_MAX_RETRIEVABLE_FILESIZE = SLikeNetJNI.SLNET_MAX_RETRIEVABLE_FILESIZE_get();
  public final static int LIBCAT_SECURITY = SLikeNetJNI.LIBCAT_SECURITY_get();
  public final static int _RAKNET_SUPPORT_ConnectionGraph2 = SLikeNetJNI._RAKNET_SUPPORT_ConnectionGraph2_get();
  public final static int _RAKNET_SUPPORT_DirectoryDeltaTransfer = SLikeNetJNI._RAKNET_SUPPORT_DirectoryDeltaTransfer_get();
  public final static int _RAKNET_SUPPORT_FileListTransfer = SLikeNetJNI._RAKNET_SUPPORT_FileListTransfer_get();
  public final static int _RAKNET_SUPPORT_FullyConnectedMesh = SLikeNetJNI._RAKNET_SUPPORT_FullyConnectedMesh_get();
  public final static int _RAKNET_SUPPORT_FullyConnectedMesh2 = SLikeNetJNI._RAKNET_SUPPORT_FullyConnectedMesh2_get();
  public final static int _RAKNET_SUPPORT_MessageFilter = SLikeNetJNI._RAKNET_SUPPORT_MessageFilter_get();
  public final static int _RAKNET_SUPPORT_NatPunchthroughClient = SLikeNetJNI._RAKNET_SUPPORT_NatPunchthroughClient_get();
  public final static int _RAKNET_SUPPORT_NatPunchthroughServer = SLikeNetJNI._RAKNET_SUPPORT_NatPunchthroughServer_get();
  public final static int _RAKNET_SUPPORT_NatTypeDetectionClient = SLikeNetJNI._RAKNET_SUPPORT_NatTypeDetectionClient_get();
  public final static int _RAKNET_SUPPORT_NatTypeDetectionServer = SLikeNetJNI._RAKNET_SUPPORT_NatTypeDetectionServer_get();
  public final static int _RAKNET_SUPPORT_PacketLogger = SLikeNetJNI._RAKNET_SUPPORT_PacketLogger_get();
  public final static int _RAKNET_SUPPORT_ReadyEvent = SLikeNetJNI._RAKNET_SUPPORT_ReadyEvent_get();
  public final static int _RAKNET_SUPPORT_ReplicaManager3 = SLikeNetJNI._RAKNET_SUPPORT_ReplicaManager3_get();
  public final static int _RAKNET_SUPPORT_Router2 = SLikeNetJNI._RAKNET_SUPPORT_Router2_get();
  public final static int _RAKNET_SUPPORT_RPC4Plugin = SLikeNetJNI._RAKNET_SUPPORT_RPC4Plugin_get();
  public final static int _RAKNET_SUPPORT_TeamBalancer = SLikeNetJNI._RAKNET_SUPPORT_TeamBalancer_get();
  public final static int _RAKNET_SUPPORT_TeamManager = SLikeNetJNI._RAKNET_SUPPORT_TeamManager_get();
  public final static int _RAKNET_SUPPORT_UDPProxyClient = SLikeNetJNI._RAKNET_SUPPORT_UDPProxyClient_get();
  public final static int _RAKNET_SUPPORT_UDPProxyCoordinator = SLikeNetJNI._RAKNET_SUPPORT_UDPProxyCoordinator_get();
  public final static int _RAKNET_SUPPORT_UDPProxyServer = SLikeNetJNI._RAKNET_SUPPORT_UDPProxyServer_get();
  public final static int _RAKNET_SUPPORT_ConsoleServer = SLikeNetJNI._RAKNET_SUPPORT_ConsoleServer_get();
  public final static int _RAKNET_SUPPORT_RakNetTransport = SLikeNetJNI._RAKNET_SUPPORT_RakNetTransport_get();
  public final static int _RAKNET_SUPPORT_TelnetTransport = SLikeNetJNI._RAKNET_SUPPORT_TelnetTransport_get();
  public final static int _RAKNET_SUPPORT_TCPInterface = SLikeNetJNI._RAKNET_SUPPORT_TCPInterface_get();
  public final static int _RAKNET_SUPPORT_LogCommandParser = SLikeNetJNI._RAKNET_SUPPORT_LogCommandParser_get();
  public final static int _RAKNET_SUPPORT_RakNetCommandParser = SLikeNetJNI._RAKNET_SUPPORT_RakNetCommandParser_get();
  public final static int _RAKNET_SUPPORT_EmailSender = SLikeNetJNI._RAKNET_SUPPORT_EmailSender_get();
  public final static int _RAKNET_SUPPORT_HTTPConnection = SLikeNetJNI._RAKNET_SUPPORT_HTTPConnection_get();
  public final static int _RAKNET_SUPPORT_HTTPConnection2 = SLikeNetJNI._RAKNET_SUPPORT_HTTPConnection2_get();
  public final static int _RAKNET_SUPPORT_PacketizedTCP = SLikeNetJNI._RAKNET_SUPPORT_PacketizedTCP_get();
  public final static int _RAKNET_SUPPORT_TwoWayAuthentication = SLikeNetJNI._RAKNET_SUPPORT_TwoWayAuthentication_get();
  public final static int _RAKNET_SUPPORT_CloudClient = SLikeNetJNI._RAKNET_SUPPORT_CloudClient_get();
  public final static int _RAKNET_SUPPORT_CloudServer = SLikeNetJNI._RAKNET_SUPPORT_CloudServer_get();
  public final static int _RAKNET_SUPPORT_DynDNS = SLikeNetJNI._RAKNET_SUPPORT_DynDNS_get();
  public final static int _RAKNET_SUPPORT_Rackspace = SLikeNetJNI._RAKNET_SUPPORT_Rackspace_get();
  public final static int _RAKNET_SUPPORT_FileOperations = SLikeNetJNI._RAKNET_SUPPORT_FileOperations_get();
  public final static int _RAKNET_SUPPORT_UDPForwarder = SLikeNetJNI._RAKNET_SUPPORT_UDPForwarder_get();
  public final static int _RAKNET_SUPPORT_StatisticsHistory = SLikeNetJNI._RAKNET_SUPPORT_StatisticsHistory_get();
  public final static int _RAKNET_SUPPORT_LibVoice = SLikeNetJNI._RAKNET_SUPPORT_LibVoice_get();
  public final static int _RAKNET_SUPPORT_RelayPlugin = SLikeNetJNI._RAKNET_SUPPORT_RelayPlugin_get();
  public final static String PRINTF_64_BIT_MODIFIER = SLikeNetJNI.PRINTF_64_BIT_MODIFIER_get();
  public final static int NETWORK_ID_MANAGER_HASH_LENGTH = SLikeNetJNI.NETWORK_ID_MANAGER_HASH_LENGTH_get();
  public final static String RAK_TIME_FORMAT_STRING = SLikeNetJNI.RAK_TIME_FORMAT_STRING_get();
  public final static int _TABLE_BPLUS_TREE_ORDER = SLikeNetJNI._TABLE_BPLUS_TREE_ORDER_get();
  public final static int _TABLE_MAX_COLUMN_NAME_LENGTH = SLikeNetJNI._TABLE_MAX_COLUMN_NAME_LENGTH_get();
  public final static int REMOTE_MAX_TEXT_INPUT = SLikeNetJNI.REMOTE_MAX_TEXT_INPUT_get();
  public final static int MESSAGE_FILTER_MAX_MESSAGE_ID = SLikeNetJNI.MESSAGE_FILTER_MAX_MESSAGE_ID_get();
}
