/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class ThreadsafePacketLogger extends PacketLogger {
  private transient long swigCPtr;

  protected ThreadsafePacketLogger(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.ThreadsafePacketLogger_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ThreadsafePacketLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_ThreadsafePacketLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ThreadsafePacketLogger() {
    this(SLikeNetJNI.new_ThreadsafePacketLogger(), true);
  }

}
