/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class UDPProxyServer extends PluginInterface2 {
  private transient long swigCPtr;

  protected UDPProxyServer(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.UDPProxyServer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UDPProxyServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_UDPProxyServer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static UDPProxyServer GetInstance() {
    long cPtr = SLikeNetJNI.UDPProxyServer_GetInstance();
    return (cPtr == 0) ? null : new UDPProxyServer(cPtr, false);
  }

  public static void DestroyInstance(UDPProxyServer i) {
    SLikeNetJNI.UDPProxyServer_DestroyInstance(UDPProxyServer.getCPtr(i), i);
  }

  public UDPProxyServer() {
    this(SLikeNetJNI.new_UDPProxyServer(), true);
  }

  public void SetSocketFamily(int _socketFamily) {
    SLikeNetJNI.UDPProxyServer_SetSocketFamily(swigCPtr, this, _socketFamily);
  }

  public void SetResultHandler(UDPProxyServerResultHandler rh) {
    SLikeNetJNI.UDPProxyServer_SetResultHandler(swigCPtr, this, UDPProxyServerResultHandler.getCPtr(rh), rh);
  }

  public boolean LoginToCoordinator(RakString password, SystemAddress coordinatorAddress) {
    return SLikeNetJNI.UDPProxyServer_LoginToCoordinator(swigCPtr, this, RakString.getCPtr(password), password, SystemAddress.getCPtr(coordinatorAddress), coordinatorAddress);
  }

  public void SetServerPublicIP(RakString ip) {
    SLikeNetJNI.UDPProxyServer_SetServerPublicIP(swigCPtr, this, RakString.getCPtr(ip), ip);
  }

  public void setUdpForwarder(UDPForwarder value) {
    SLikeNetJNI.UDPProxyServer_udpForwarder_set(swigCPtr, this, UDPForwarder.getCPtr(value), value);
  }

  public UDPForwarder getUdpForwarder() {
    long cPtr = SLikeNetJNI.UDPProxyServer_udpForwarder_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UDPForwarder(cPtr, false);
  }

}
