/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class UDPProxyClientResultHandler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UDPProxyClientResultHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UDPProxyClientResultHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_UDPProxyClientResultHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void OnForwardingSuccess(String proxyIPAddress, int proxyPort, SystemAddress proxyCoordinator, SystemAddress sourceAddress, SystemAddress targetAddress, RakNetGUID targetGuid, UDPProxyClient proxyClientPlugin) {
    SLikeNetJNI.UDPProxyClientResultHandler_OnForwardingSuccess(swigCPtr, this, proxyIPAddress, proxyPort, SystemAddress.getCPtr(proxyCoordinator), proxyCoordinator, SystemAddress.getCPtr(sourceAddress), sourceAddress, SystemAddress.getCPtr(targetAddress), targetAddress, RakNetGUID.getCPtr(targetGuid), targetGuid, UDPProxyClient.getCPtr(proxyClientPlugin), proxyClientPlugin);
  }

  public void OnForwardingNotification(String proxyIPAddress, int proxyPort, SystemAddress proxyCoordinator, SystemAddress sourceAddress, SystemAddress targetAddress, RakNetGUID targetGuid, UDPProxyClient proxyClientPlugin) {
    SLikeNetJNI.UDPProxyClientResultHandler_OnForwardingNotification(swigCPtr, this, proxyIPAddress, proxyPort, SystemAddress.getCPtr(proxyCoordinator), proxyCoordinator, SystemAddress.getCPtr(sourceAddress), sourceAddress, SystemAddress.getCPtr(targetAddress), targetAddress, RakNetGUID.getCPtr(targetGuid), targetGuid, UDPProxyClient.getCPtr(proxyClientPlugin), proxyClientPlugin);
  }

  public void OnNoServersOnline(SystemAddress proxyCoordinator, SystemAddress sourceAddress, SystemAddress targetAddress, RakNetGUID targetGuid, UDPProxyClient proxyClientPlugin) {
    SLikeNetJNI.UDPProxyClientResultHandler_OnNoServersOnline(swigCPtr, this, SystemAddress.getCPtr(proxyCoordinator), proxyCoordinator, SystemAddress.getCPtr(sourceAddress), sourceAddress, SystemAddress.getCPtr(targetAddress), targetAddress, RakNetGUID.getCPtr(targetGuid), targetGuid, UDPProxyClient.getCPtr(proxyClientPlugin), proxyClientPlugin);
  }

  public void OnRecipientNotConnected(SystemAddress proxyCoordinator, SystemAddress sourceAddress, SystemAddress targetAddress, RakNetGUID targetGuid, UDPProxyClient proxyClientPlugin) {
    SLikeNetJNI.UDPProxyClientResultHandler_OnRecipientNotConnected(swigCPtr, this, SystemAddress.getCPtr(proxyCoordinator), proxyCoordinator, SystemAddress.getCPtr(sourceAddress), sourceAddress, SystemAddress.getCPtr(targetAddress), targetAddress, RakNetGUID.getCPtr(targetGuid), targetGuid, UDPProxyClient.getCPtr(proxyClientPlugin), proxyClientPlugin);
  }

  public void OnAllServersBusy(SystemAddress proxyCoordinator, SystemAddress sourceAddress, SystemAddress targetAddress, RakNetGUID targetGuid, UDPProxyClient proxyClientPlugin) {
    SLikeNetJNI.UDPProxyClientResultHandler_OnAllServersBusy(swigCPtr, this, SystemAddress.getCPtr(proxyCoordinator), proxyCoordinator, SystemAddress.getCPtr(sourceAddress), sourceAddress, SystemAddress.getCPtr(targetAddress), targetAddress, RakNetGUID.getCPtr(targetGuid), targetGuid, UDPProxyClient.getCPtr(proxyClientPlugin), proxyClientPlugin);
  }

  public void OnForwardingInProgress(String proxyIPAddress, int proxyPort, SystemAddress proxyCoordinator, SystemAddress sourceAddress, SystemAddress targetAddress, RakNetGUID targetGuid, UDPProxyClient proxyClientPlugin) {
    SLikeNetJNI.UDPProxyClientResultHandler_OnForwardingInProgress(swigCPtr, this, proxyIPAddress, proxyPort, SystemAddress.getCPtr(proxyCoordinator), proxyCoordinator, SystemAddress.getCPtr(sourceAddress), sourceAddress, SystemAddress.getCPtr(targetAddress), targetAddress, RakNetGUID.getCPtr(targetGuid), targetGuid, UDPProxyClient.getCPtr(proxyClientPlugin), proxyClientPlugin);
  }

}
