/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class UDPProxyCoordinator extends PluginInterface2 {
  private transient long swigCPtr;

  protected UDPProxyCoordinator(long cPtr, boolean cMemoryOwn) {
    super(SLikeNetJNI.UDPProxyCoordinator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UDPProxyCoordinator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_UDPProxyCoordinator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static UDPProxyCoordinator GetInstance() {
    long cPtr = SLikeNetJNI.UDPProxyCoordinator_GetInstance();
    return (cPtr == 0) ? null : new UDPProxyCoordinator(cPtr, false);
  }

  public static void DestroyInstance(UDPProxyCoordinator i) {
    SLikeNetJNI.UDPProxyCoordinator_DestroyInstance(UDPProxyCoordinator.getCPtr(i), i);
  }

  public UDPProxyCoordinator() {
    this(SLikeNetJNI.new_UDPProxyCoordinator(), true);
  }

  public void SetRemoteLoginPassword(RakString password) {
    SLikeNetJNI.UDPProxyCoordinator_SetRemoteLoginPassword(swigCPtr, this, RakString.getCPtr(password), password);
  }

  static public class SenderAndTargetAddress {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected SenderAndTargetAddress(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(SenderAndTargetAddress obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SLikeNetJNI.delete_UDPProxyCoordinator_SenderAndTargetAddress(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setSenderClientAddress(SystemAddress value) {
      SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_senderClientAddress_set(swigCPtr, this, SystemAddress.getCPtr(value), value);
    }
  
    public SystemAddress getSenderClientAddress() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_senderClientAddress_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SystemAddress(cPtr, false);
    }
  
    public void setSenderClientGuid(RakNetGUID value) {
      SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_senderClientGuid_set(swigCPtr, this, RakNetGUID.getCPtr(value), value);
    }
  
    public RakNetGUID getSenderClientGuid() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_senderClientGuid_get(swigCPtr, this);
      return (cPtr == 0) ? null : new RakNetGUID(cPtr, false);
    }
  
    public void setTargetClientAddress(SystemAddress value) {
      SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_targetClientAddress_set(swigCPtr, this, SystemAddress.getCPtr(value), value);
    }
  
    public SystemAddress getTargetClientAddress() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_targetClientAddress_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SystemAddress(cPtr, false);
    }
  
    public void setTargetClientGuid(RakNetGUID value) {
      SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_targetClientGuid_set(swigCPtr, this, RakNetGUID.getCPtr(value), value);
    }
  
    public RakNetGUID getTargetClientGuid() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_SenderAndTargetAddress_targetClientGuid_get(swigCPtr, this);
      return (cPtr == 0) ? null : new RakNetGUID(cPtr, false);
    }
  
    public SenderAndTargetAddress() {
      this(SLikeNetJNI.new_UDPProxyCoordinator_SenderAndTargetAddress(), true);
    }
  
  }

  static public class ServerWithPing {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected ServerWithPing(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(ServerWithPing obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SLikeNetJNI.delete_UDPProxyCoordinator_ServerWithPing(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setPing(int value) {
      SLikeNetJNI.UDPProxyCoordinator_ServerWithPing_ping_set(swigCPtr, this, value);
    }
  
    public int getPing() {
      return SLikeNetJNI.UDPProxyCoordinator_ServerWithPing_ping_get(swigCPtr, this);
    }
  
    public void setServerAddress(SystemAddress value) {
      SLikeNetJNI.UDPProxyCoordinator_ServerWithPing_serverAddress_set(swigCPtr, this, SystemAddress.getCPtr(value), value);
    }
  
    public SystemAddress getServerAddress() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ServerWithPing_serverAddress_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SystemAddress(cPtr, false);
    }
  
    public ServerWithPing() {
      this(SLikeNetJNI.new_UDPProxyCoordinator_ServerWithPing(), true);
    }
  
  }

  static public class ForwardingRequest {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected ForwardingRequest(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(ForwardingRequest obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SLikeNetJNI.delete_UDPProxyCoordinator_ForwardingRequest(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setTimeoutOnNoDataMS(SWIGTYPE_p_unsigned___int32 value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_timeoutOnNoDataMS_set(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(value));
    }
  
    public SWIGTYPE_p_unsigned___int32 getTimeoutOnNoDataMS() {
      return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_timeoutOnNoDataMS_get(swigCPtr, this), true);
    }
  
    public void setTimeoutAfterSuccess(SWIGTYPE_p_unsigned___int32 value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_timeoutAfterSuccess_set(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(value));
    }
  
    public SWIGTYPE_p_unsigned___int32 getTimeoutAfterSuccess() {
      return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_timeoutAfterSuccess_get(swigCPtr, this), true);
    }
  
    public void setSata(UDPProxyCoordinator.SenderAndTargetAddress value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_sata_set(swigCPtr, this, UDPProxyCoordinator.SenderAndTargetAddress.getCPtr(value), value);
    }
  
    public UDPProxyCoordinator.SenderAndTargetAddress getSata() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_sata_get(swigCPtr, this);
      return (cPtr == 0) ? null : new UDPProxyCoordinator.SenderAndTargetAddress(cPtr, false);
    }
  
    public void setRequestingAddress(SystemAddress value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_requestingAddress_set(swigCPtr, this, SystemAddress.getCPtr(value), value);
    }
  
    public SystemAddress getRequestingAddress() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_requestingAddress_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SystemAddress(cPtr, false);
    }
  
    public void setCurrentlyAttemptedServerAddress(SystemAddress value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_currentlyAttemptedServerAddress_set(swigCPtr, this, SystemAddress.getCPtr(value), value);
    }
  
    public SystemAddress getCurrentlyAttemptedServerAddress() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_currentlyAttemptedServerAddress_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SystemAddress(cPtr, false);
    }
  
    public void setRemainingServersToTry(SWIGTYPE_p_DataStructures__QueueT_SLNet__SystemAddress_t value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_remainingServersToTry_set(swigCPtr, this, SWIGTYPE_p_DataStructures__QueueT_SLNet__SystemAddress_t.getCPtr(value));
    }
  
    public SWIGTYPE_p_DataStructures__QueueT_SLNet__SystemAddress_t getRemainingServersToTry() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_remainingServersToTry_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_DataStructures__QueueT_SLNet__SystemAddress_t(cPtr, false);
    }
  
    public BitStream getServerSelectionBitstream() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_serverSelectionBitstream_get(swigCPtr, this);
      return (cPtr == 0) ? null : new BitStream(cPtr, false);
    }
  
    public void setSourceServerPings(SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_sourceServerPings_set(swigCPtr, this, SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t.getCPtr(value));
    }
  
    public SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t getSourceServerPings() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_sourceServerPings_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t(cPtr, false);
    }
  
    public void setTargetServerPings(SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_targetServerPings_set(swigCPtr, this, SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t.getCPtr(value));
    }
  
    public SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t getTargetServerPings() {
      long cPtr = SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_targetServerPings_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_DataStructures__ListT_SLNet__UDPProxyCoordinator__ServerWithPing_t(cPtr, false);
    }
  
    public void setTimeRequestedPings(SWIGTYPE_p_unsigned___int32 value) {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_timeRequestedPings_set(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(value));
    }
  
    public SWIGTYPE_p_unsigned___int32 getTimeRequestedPings() {
      return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_timeRequestedPings_get(swigCPtr, this), true);
    }
  
    public void OrderRemainingServersToTry() {
      SLikeNetJNI.UDPProxyCoordinator_ForwardingRequest_OrderRemainingServersToTry(swigCPtr, this);
    }
  
    public ForwardingRequest() {
      this(SLikeNetJNI.new_UDPProxyCoordinator_ForwardingRequest(), true);
    }
  
  }

}
