/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.justagod.slikenet;

public class uint24_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected uint24_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(uint24_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SLikeNetJNI.delete_uint24_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVal(SWIGTYPE_p_unsigned___int32 value) {
    SLikeNetJNI.uint24_t_val_set(swigCPtr, this, SWIGTYPE_p_unsigned___int32.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned___int32 getVal() {
    return new SWIGTYPE_p_unsigned___int32(SLikeNetJNI.uint24_t_val_get(swigCPtr, this), true);
  }

  public uint24_t() {
    this(SLikeNetJNI.new_uint24_t__SWIG_0(), true);
  }

  public uint24_t(uint24_t a) {
    this(SLikeNetJNI.new_uint24_t__SWIG_1(uint24_t.getCPtr(a), a), true);
  }

  public uint24_t(SWIGTYPE_p_unsigned___int32 a) {
    this(SLikeNetJNI.new_uint24_t__SWIG_2(SWIGTYPE_p_unsigned___int32.getCPtr(a)), true);
  }

}
