/*
 * This file was generated by the Gradle 'init' task.
 */

import java.net.URI;


apply(plugin = "java")
apply(plugin = "kotlin")
apply(plugin = "idea")

repositories {
    mavenLocal()
    maven {
        url = URI("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = URI("http://repo.maven.apache.org/maven2")
    }
}

dependencies {
    add("implementation", "org.apache.maven:maven-plugin-api:3.5.4")
    add("implementation", "org.apache.maven.plugin-tools:maven-plugin-annotations:3.5.2")
    add("implementation", "org.apache.maven:maven-core:3.0")
    add("implementation", "junit:junit:4.12")
    add("implementation", "org.slf4j:slf4j-simple:1.7.25")
    add("compileOnly", "org.osgi:osgi.annotation:7.0.0")
}

group = "org.bytedeco"
version = "1.5.3-SNAPSHOT"
description = "JavaCPP"

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_7
}


tasks.withType(JavaCompile::class.java) {
    options.encoding = "UTF-8"
}
